### ISSUE TITLE
pfSimpleSort not included in bower dist 2.2.1

### ISSUE THREAD

**Issue by AllenBW** [patternfly/angular-patternfly#102]
When installing angular-patternfly v2.2.1 via bower,  angular-patternfly.js is missing the pfSimpleSort directive.

**Comment by jeff-phillips-18** [comment]
pfSimpleSort was added after 2.2.1 was released. It is in the master repo and will be included in the next release.

**Comment by jeff-phillips-18** [comment]
pfSimpleSort is now available in 2.3.0
