### ISSUE TITLE
pfCard directive should not show heading area if no title is given.

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/angular-patternfly#103]
If I try to create a card with no title, I get a blank area and a separator above my content.

**Comment by dtaylor113** [comment]
Can you post the HTML you are using?

**Comment by jeff-phillips-18** [comment]
<div pf-card show-top-border="true">
        <span> HELLO THERE </span>
      </div>

**Comment by dtaylor113** [comment]
Fixed via #106
