### ISSUE TITLE
pfCard footer should be refactored out of pfCard

### ISSUE THREAD

**Issue by waldenraines** [patternfly/angular-patternfly#105]
Instead of using a string in a config object we should use directives and transclude the content of the directive into the appropriate sections.  Either that or we could look into using [angular-blocks](https://github.com/wmluke/angular-blocks).

See also https://github.com/patternfly/angular-patternfly/pull/100#issuecomment-143237400

**Comment by serenamarie125** [comment]
@waldenraines the goal in supplying these directives is to promote consistency.  I'd rather ask for requests of specific content that we may have missed per this design and see if there's a way that we can provide it.  We don't want to promote the ability to allow complete customization, since that will promote inconsistency.

**Comment by waldenraines** [comment]
@serenamarie125 I understand that goal and I wonder if there is a way that we can balance that with AngularJS best practices.

I'm not arguing for "complete customization", I'm arguing for using AngularJS best practices instead of a monolithic configuration object.

If we want to be strict on the customization we can still achieve this while using Angular the way it was meant to be used (note the new `pf-icon-text` directive):

```html
<div pf-card head-title="Performance" sub-title="Last 30 Days" show-top-border="false" show-titles-separator="false">
  <div pf-trends-chart config="configVirtual" chart-data="dataVirtual"></div>
  <div pf-trends-chart config="configPhysical" chart-data="dataPhysical"></div>
  <div pf-trends-chart config="configMemory" chart-data="dataMemory"></div>
  <div pf-card-footer>
    <div pf-icon-link="fa fa-plus-circle">
      Add New Cluster
    </div>
  </div>
</div>
```

Where `pf-icon-link` transcludes the "Add New Cluster" text next to the icon.  This should not be a part of some config, it should be expressed declaratively in the HTML.  This allows the consumer of angular-patternfly to easily translate this text, for example, while still maintaining the layout of the pattern.

I will change the name of this issue to reflect the actual problem here.
