### ISSUE TITLE
Move to Angular 1.3.x?

### ISSUE THREAD

**Issue by mtho11** [patternfly/angular-patternfly#15]
Are there intentions to move to Angular 1.3.x. Just wanting to remove resolutions in our bower file.

**Comment by mtho11** [comment]
CC @vrockai

**Comment by kenfinnigan** [comment]
There's no objections from me.

By all means submit a PR with the change

**Comment by vrockai** [comment]
I'll make that next week.

**Comment by vrockai** [comment]
https://github.com/patternfly/angular-patternfly/pull/16

**Comment by kenfinnigan** [comment]
@mtho11 0.0.5 is now released
