### ISSUE TITLE
most bower devDependencies should be dependencies

### ISSUE THREAD

**Issue by himdel** [patternfly/angular-patternfly#151]
Bower's `devDependencies` are meant for things needed only for development, tests, etc. Packages that are actually depended upon for the daily operation should be listed as `dependencies` instead. (That's according to the [bower spec](https://github.com/bower/spec/blob/master/json.md#user-content-devdependencies).)

Right now, angular-patternfly's bower.json has no dependencies and everything in devDependencies, but I **think** there are no real devDependencies and everything should be a dependency. But I'm quite sure that since [charts](https://github.com/patternfly/angular-patternfly/blob/master/src/charts/charts.module.js) depends on ui.bootstrap and ngSanitize, at least angular-sanitize and angular-bootstrap should definitely be in dependencies..

**Comment by vrockai** [comment]
+1 on this. Setting the dependencies correctly in the angular-patternfly bower.json is crucial for [wiredep](https://github.com/taptapship/wiredep) to work correctly.

**Comment by dtaylor113** [comment]
Hi, we have created the JIRA story below and we will prioritize it in our backlog

https://patternfly.atlassian.net/browse/PTNFLY-1107

Thanks,
- Dave Taylor

**Comment by dtaylor113** [comment]
Hi,
I believe this was addressed in commit:
https://github.com/patternfly/angular-patternfly/commit/5309c44a904f42c39ebf79498ec43ad145d21e61

This should be included in angular-patternfly v2.10.0.

Thanks,
- Dave
