### ISSUE TITLE
patternfly new component

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [patternfly/angular-patternfly#169]
hi, 
when wa can use the new component of patternfly as liste view toast ....  ?
is not in github repository !
thanks

**Comment by dtaylor113** [comment]
Hi,
Can you please elaborate what component you are looking for?
Is it "list view" and/or "toast notifications"?
Thanks,
- Dave

**Comment by dtaylor113** [comment]
As of angular-patternfly v3.1.0 the "list view" and "toast notifications" should be available.
Thanks,
Dave
