### ISSUE TITLE
support for angular-ui 1.x version

### ISSUE THREAD

**Issue by jkandasa** [patternfly/angular-patternfly#175]
current version of angular-patternfly v2.9.0 not fully functional with angular-ui v1.x.

**Comment by jeff-phillips-18** [comment]
@jkandasa  Could you elaborate please?

**Comment by jkandasa** [comment]
I was using  `angular-patternfly` with `angular-ui v0.14.x` throws the following deprecated messages and work good.   

```
$tooltip is now deprecated. Use $uibTooltip instead.
angular.js:12416 DropdownController is now deprecated. Use UibDropdownController instead.
angular.js:12416 dropdown-toggle is now deprecated. Use uib-dropdown-toggle instead.
angular.js:12416 dropdown-menu is now deprecated. Use uib-dropdown-menu instead.
angular.js:12416 dropdown is now deprecated. Use uib-dropdown instead.
angular.js:12416 tooltip-popup is now deprecated. Use uib-tooltip-popup instead.
angular.js:12416 DropdownController is now deprecated. Use UibDropdownController instead.
angular.js:12416 dropdown-toggle is now deprecated. Use uib-dropdown-toggle instead.
angular.js:12416 dropdown-menu is now deprecated. Use uib-dropdown-menu instead.
angular.js:12416 dropdown is now deprecated. Use uib-dropdown instead.
```

When I move to `angular-ui v1.x` some functions are not working, example drop down not working for `pfSimpleFilter`.

I guess we have to rename deprecated variables to support latest release of `angular-ui`

**Comment by jkandasa** [comment]
`HeatMap` chart tooltip is not working with `angular-ui-bootstrap` version `0.14.3`

**Comment by jkandasa** [comment]
@jeff-phillips-18 Any plan to support recent version of `angular-ui-bootstrap` in near future?

**Comment by jeff-phillips-18** [comment]
Now using angular-bootstrap 2.2.x
