### ISSUE TITLE
pfSelect doesn't react to ng-options change

### ISSUE THREAD

**Issue by ammendonca** [patternfly/angular-patternfly#177]
When the ng-options changes, the hidden <select> element is correctly updated to reflect the change (as tested in https://github.com/patternfly/angular-patternfly/blob/aa38a2806d2df0f3ed156668104f4bd966707f82/test/select/select.spec.js#L44) but the generated dropdown (which is what's displayed in the browser) is not, and remains with the old options.

This should be fixed and the test should test for it as well.

**Comment by dtaylor113** [comment]
Hi,
We have created a JIRA issue to track this bug:
https://patternfly.atlassian.net/browse/PTNFLY-1122

We will prioritize this work in our upcoming sprints. 
Thank you,
- Dave Taylor

**Comment by dtaylor113** [comment]
I believe this was fixed with pull request:
https://github.com/patternfly/angular-patternfly/commit/8484123fcbbf5ef0c6b8f87cca527d678a70e9b0
