### ISSUE TITLE
LICENSE.txt?

### ISSUE THREAD

**Issue by jlandry** [patternfly/angular-patternfly#190]
I would assume Angular-Patternfly to be under the Apache 2.0 License because Patternfly itself is but Angular-Patternfly does not have a license.txt.  

What license is Angular-Patternfly intended to be used under?

**Comment by dtaylor113** [comment]
Hi, yes I believe that is correct.  We will add a license.txt file to the angular-patternfly repo.
Thank you for bringing this to our attention.

**Comment by dtaylor113** [comment]
Hi, 
We added an "Apache 2.0" LICENSE.txt file to the angular-patternfly repo. 45a43b74dfc563c97951d37cc991126c2cf9fb0e

Thanks,
Dave
