### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mebert** [patternfly/angular-patternfly#191]
What is the license for Angular Patternfly

**Comment by dtaylor113** [comment]
Hi,
I believe angular-patternfly should be the same licensing as patternfly which is an Apache 2.0 License.  We will add a license.txt file to the angular-patternfly repo.
Thank you

**Comment by dtaylor113** [comment]
Hi, 
We added an "Apache 2.0" LICENSE.txt file to the angular-patternfly repo. 45a43b74dfc563c97951d37cc991126c2cf9fb0e

Thanks,
Dave
