### ISSUE TITLE
Incompatibility with patternfly-sass 3.x

### ISSUE THREAD

**Issue by skateman** [patternfly/angular-patternfly#194]
Specifying `patternfly` as a [dependency](https://github.com/patternfly/angular-patternfly/blob/master/bower.json#L42) in this project causes SASS **load path issues** when used with patternfly-sass in a Rails application. My suggestion would be to create a fork or a special version calles *angular-patternfly-sass* where the `bower.json` and `package.json` files specify `patternfly-sass` as a dependency instead of `patternfly`.

Could you somehow fix this? I can help with testing by trying to integrate it into our application.

**Comment by skateman** [comment]
cc @dclarizio @epwinchell @martinpovolny @himdel

**Comment by martinpovolny** [comment]
Well it would be nice if we could actually consume the Patterfly stuff w/o having to modify it.

Who are all the patternfly consumers and how do they consule Patternfly anyway?

**Comment by skateman** [comment]
I created a -sass version of this package with fixed dependencies:
https://github.com/patternfly/angular-patternfly-sass
