### ISSUE TITLE
Have to tap pf-sort dropdown twice on iOS

### ISSUE THREAD

**Issue by spadgett** [patternfly/angular-patternfly#212]
Mobile Safari will treat the first tap as a hover and only open the dropdown on the second tap. Also the tooltip overlays the dropdown items.

<img width="487" alt="screen shot 2016-03-23 at 3 39 34 pm" src="https://cloud.githubusercontent.com/assets/1167259/13998411/8004fe6e-f10d-11e5-855f-46ff9e16c472.png">

/cc @jwforres @rhamilto

**Comment by rhamilto** [comment]
> Also the tooltip overlays the dropdown items.

So it sounds like we need to request the Angular-PatternFly directive has a tooltip position option?

**Comment by spadgett** [comment]
> Also the tooltip overlays the dropdown items.

I can reproduce on a desktop as well.

![screen shot 2016-03-23 at 3 48 23 pm](https://cloud.githubusercontent.com/assets/1167259/13998674/c80df084-f10e-11e5-996e-b6a0670ad0d1.png)

> So it sounds like we need to request the Angular-PatternFly directive has a tooltip position option?

Tooltips don't work well on mobile, particularly on buttons. If the dropdown is confusing, does it deserve a label instead?

**Comment by benjaminapetersen** [comment]
IMHO, i'd rather there be a label   `"sort by:  <dropdown>"`

**Comment by benjaminapetersen** [comment]
So a "tooltip position" option may not be necessary, since the dropdown drops down & there are controls to left and right, prob the position should just be top?

Otherwise, if I were going to control it I'd want something like:
```html
<!-- no tooltip -->
<pf-sort
 config="config"></pf-sort>

<!-- default tooltip (top) -->
 <pf-sort
  config="config"
  sortby-tooltip></pf-sort>

<!-- positioned tooltip -->
 <pf-sort
  config="config"
  sortby-tooltip="left"></pf-sort>

```
If its added to a `div` instead of as a standalone node, I suppose it should be namespaced so it doesn't clash with other directives on the node:
```html
 <div
  pf-sort
  pf-sort-config="config"
  pf-sort-sortby-tooltip="left"></div>
```

The `config` attr could possibly be collapsed into `<div pf-sort="config">`, that would also follow some common conventions, but is tangental.

**Comment by benjaminapetersen** [comment]
Files to fix for reference: https://github.com/patternfly/angular-patternfly/tree/master/src/sort
@MarkDeMaria

**Comment by spadgett** [comment]
Positioning the tooltip elsewhere doesn't fix the iOS problem where you have to tap twice.

@ajacobs21e Suggested removing the tooltip altogether, which I think is a better solution.

**Comment by benjaminapetersen** [comment]
True, and thats prob the most bothersome. 
Sounds good!
