### ISSUE TITLE
Make angular-patternfly available in node packages

### ISSUE THREAD

**Issue by karelhala** [patternfly/angular-patternfly#215]
We are trying to port some things to angular in ManageIq and for that we use custom ui components which depends on angular patternfly, but we are trying to use only npm for managing these custom ui components. So it would be nice if this repository would be also available in node packages and not only at bower.

**Comment by dtaylor113** [comment]
Hi,
I do not see a npm for 'angular-sanitize', and I only see an unofficial npm for 'angular-bootstrap', so I'm not sure angular-patternfly can be installed via npm only.

**Comment by SebastianBerc** [comment]
https://www.npmjs.com/package/angular-sanitize

**Comment by karelhala** [comment]
Well we used [Bower webpack plugin](https://www.npmjs.com/package/bower-webpack-plugin ) eventually, but it would be really nice to have angular patternfly as node package since it looks like JS world is slowly shifting towards node.

**Comment by mtho11** [comment]
Not having angular-patternfly as npm is essentially a gating factor to Angular 2 usage.

**Comment by dtaylor113** [comment]
Just found an official NPM package for angular-bootstrap :-)

https://www.npmjs.com/package/angular-ui-bootstrap

**Comment by jeff-phillips-18** [comment]
Done
