### ISSUE TITLE
[Feature request] Allow heat maps to order by id or value

### ISSUE THREAD

**Issue by giovtorres** [patternfly/angular-patternfly#262]
I've written a javascript monitoring application for an HPC cluster that uses D3 to create an SVG heatmap.  I've been considering migrating to Patternfly because it looks very clean, modern and, most of all, I wouldn't have to do as much CSS work! :)

My heatmap is ordered by hostname, not by their respective cpu load values.

I like the Patternfly heatmap, but please consider adding the option to choose the ordering by either id or value.

Thanks,
Giovanni

**Comment by dlabrecq** [comment]
Can you please clarify how ordering by ID would help you? What syntax would an ID have in order to provide meaning to a heat map?

**Comment by giovtorres** [comment]
Here's a screenshot of the heatmap I've made manually.  It is ordered by hostname, not by value.  The color of each node is still represented by the value, just the ordering is done by id. It would lose some meaning to us if it were ordered by value, i.e. cpu load.

![heatmap](https://cloud.githubusercontent.com/assets/4281845/16916454/e40a1af2-4cca-11e6-80a6-332a303dd5f7.png)
