### ISSUE TITLE
Bower.json 'main' has minified and unminified files

### ISSUE THREAD

**Issue by stackus** [patternfly/angular-patternfly#27]
The main section for bower.json lists both the unminified and minified versions of the code. Are both really needed? 

We're using wiredep to include our bower components automatically and it is picking up both of these files.

**Comment by erundle** [comment]
I took a look at the other angular projects and it looks like they only include the non minified version in main even though the send down the minified and unminified files. Ex: Angular just has "main": "./angular.js", but sends down angular.js and angular.min.js. Would "main": "dist/angular-patternfly.js" be sufficient for you?

**Comment by stackus** [comment]
It would work great! Either would work but having the non-minified version helps with debugging.
