### ISSUE TITLE
Unable to get the donut - pfC3Chart - from  API Documentation

### ISSUE THREAD

**Issue by fhornain** [patternfly/angular-patternfly#270]
Hi,
Well,  I followed the setup instruction given at the following URL  - https://github.com/patternfly/angular-patternfly -
Then I tried the example given at the following API documentation page -  http://angular-patternfly.rhcloud.com/#/api/patternfly.charts.directive:pfC3Chart -.
I created a index.html as well as a script.js files but was never able to get the same outcome show at the bottom of the same documentation web page.
What did I do wrong ?

**Comment by dtaylor113** [comment]
Hi, if you would like the donut chart, please follow the donut chart example:  http://angular-patternfly.rhcloud.com/#/api/patternfly.charts.directive:pfDonutPctChart
HTH,
- Dave

**Comment by rhwood** [comment]
FWIW, to make a donut charts with three segments, I did the following (this has been simplified a little from my production code):
```
    $scope.chartConfig = {};
    $scope.chart = {};
    var getChartConfig = function(min) {
      var chartConfig = $().c3ChartDefaults().getDefaultDonutConfig();
      chartConfig.data = {
        type: 'donut',
        colors: {
          Active: $.pfPaletteColors.green,
          Idle: $.pfPaletteColors.orange,
          Off: $.pfPaletteColors.red
        },
        columns: [
          ['Active', 37],
          ['Idle', 78],
          ['Off', 42]
        ],
        groups: [
          ['active', 'idle', 'off']
        ],
        order: null,
        dataAvailable: false
      };
      chartConfig.legend = {
        show: true,
        position: 'bottom'
      };
      chartConfig.tooltip = {
        contents: $().pfDonutTooltipContents
      };
      return chartConfig;
    }
    $scope.chartConfig.min15 = getChartConfig(15);
    $scope.getChart15 = function (chart) {
      $scope.chart.min15 = chart;
    };
```
and my html is:
```
<div pf-c3-chart id="clientGauge15" config="chartConfig.min15" get-chart-callback="getChart15"></div>
```

**Comment by dtaylor113** [comment]
Hi, we have a specific angular directive for donut charts which may be easier for you to use.  Please see: https://www.patternfly.org/pattern-library/data-visualization/donut-chart/#/api

**Comment by rhwood** [comment]
How do I implement the [Relationship of a Set of Values to a Whole](http://www.patternfly.org/pattern-library/data-visualization/donut-chart/#/example-code-2) pattern using the Angular PF API?

The API documentation shows that the Angular PF donut charts only implement the [Utilization](http://www.patternfly.org/pattern-library/data-visualization/donut-chart/#/example-code-1) pattern (the only data values can be "used" and "total", which is not the pattern I'm needing to implement.

**Comment by vitorsilvalima** [comment]
This really needs to be implemented in Angular PF

**Comment by dtaylor113** [comment]
Hi, we just put up PR #450 for "Donut Chart: Relationship of a Set of Values to a Whole"
