### ISSUE TITLE
Cannot disable the kebab dropdown in pf-list-view

### ISSUE THREAD

**Issue by AparnaKarve** [patternfly/angular-patternfly#306]
I have a use case where I need to either hide or disable the kebab dropdown in the PF list view.

I noticed that there is a `ng-class="{'disabled': checkDisabled(item)}"` in the generated html to disable the kebab dropdown as shown below, which does not work.

``` html
<button class="btn btn-link dropdown-toggle" type="button" id="dropdownKebabRight_0" ng-class="{'disabled': checkDisabled(item)}" ng-click="setupActions(item, $event)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fa fa-ellipsis-v"></span></button>
```

Also, is there an option to hide the kebab dropdown based on a condition?

/cc @jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
@AparnaKarve Please checkout #324 to see if this will meet your needs.
