### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by AllenBW** [patternfly/angular-patternfly#314]
The low hanging fruit, updating 
`"lodash": "3.9.0"` to `"lodash": "4.15.0"`

Not so long hanging fruit, updating
`"angular-bootstrap": "0.13.3"` to `"angular-bootstrap": "2.1.3"`

Known breaking changes in the latter renaming of library components to include the `uib-` prefix.

**Comment by karianna** [comment]
+1 - We'd like to move to the latest supported angular-bootstrap library.

**Comment by karianna** [comment]
Perhaps a small bump to 0.14.3 could be made?  That would bring it in line with the latest version before the major jump and would clean up much of the $modal vs $uibModal type confusion

**Comment by dtaylor113** [comment]
Hi, we've upgraded to the latest lodash and angular-bootstrap in angular-patternfly v4.x.  I do not believe there are any plans to upgrade angular-patternfly v3.x.  Please reopen this issue if you need angular-patternfly v3.x to be upgraded to latest lodash and/or angular-bootstrap. -thanks

**Comment by karianna** [comment]
@dtaylor113 What's the approximate release date for v4.x and will it be 1-2-1 feature comparable to 3.x on day one?  If it's a long time away then I'd like to have this re-opened.

**Comment by dtaylor113** [comment]
Hi @karianna, we just released v4.0.0-rc.1 (branch-4.0-dev).  All the components from 3.x are available in 4.x.  The main purpose of v4.x is to switch to Angular 1.4 directives to 1.5 components: https://github.com/patternfly/angular-patternfly/blob/branch-4.0-dev/component-conversion.md

This partial changelog discusses some of the dependency updates in v4.x: https://github.com/patternfly/angular-patternfly/blob/branch-4.0-dev/CHANGELOG.md 

@bleathem, could you please elaborate on the official release date of v4.x?  -thanks!
