### ISSUE TITLE
pfSort dropdown does not indicated selected state

### ISSUE THREAD

**Issue by rhamilto** [patternfly/angular-patternfly#318]
PatternFly's dropdowns indicate an item is selected by turning the item blue with white text.  pfSort's dropdowns lack this behavior.

PatternFly Bootstrap-select example with the selected indicator
<img width="739" alt="screen shot 2016-09-26 at 10 00 18 am" src="https://cloud.githubusercontent.com/assets/895728/18836964/1a4fa2ee-83d0-11e6-90eb-99397afc2dd5.PNG">

pfSort lacks the selected indicator
<img width="178" alt="screen shot 2016-09-26 at 10 01 30 am" src="https://cloud.githubusercontent.com/assets/895728/18837005/38b33d7c-83d0-11e6-9e83-a48842641d51.PNG">

cc: @jwforres, @spadgett, @sg00dwin

**Comment by jeff-phillips-18** [comment]
Fixed by https://github.com/patternfly/patternfly/issues/503
