### ISSUE TITLE
Utilization Bar Card Filters default position value

### ISSUE THREAD

**Issue by gustavogarayalde** [patternfly/angular-patternfly#319]
The filters for the "Utilization Bar Card" is not showing unless a position is defined in the filters declaration.

The [documentation ](https://www.patternfly.org/pattern-library/cards/utilization-bar-card/#/angular) is out to date, the position property is not explained.

Example: 
`<div pf-card head-title="{{chartConfig.chartTitle}}" show-top-border="true" filter="chartConfig.periodPicker" style="width: 33%">`

Where:
`periodPicker = {
                filters: [
                    {label:'Últimos 15 días', value: '15'},
                    {label:'Últimos 30 días', value: '30'},
                    {label:'Últimos 60 días', value: '60'}
                ],
                callBackFn: function (f) {
                    console.debug( $scope );
                    alert("Filter Callback Fn Called for '" + f.label + "' value = " + f.value);
                },
                defaultFilter: '0',
                position: 'header' // --> this is making it appear... it should be the default value
            }`

**Comment by jeff-phillips-18** [comment]
http://www.patternfly.org/angular-patternfly/#/api/patternfly.card.component:pfCard%20-%20Timeframe%20Filters is the out of date documentation that does not explain the position field of the filter configuration properties. 

Agreed, there should be a default value.

**Comment by dtaylor113** [comment]
Hi, I'm a little confused.  If you do not specify a position, the default is 'footer' -meaning the filter dropdown will appear in the footer.  This is show by the "Footer with Link & Timeframe filter" example which doesn't specify a position, but by default the time filter dropdown appears in the footer.
