### ISSUE TITLE
Enclose all angular-patternfly directives in IIFE's

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/angular-patternfly#332]
Similar to PR #331, enclose all a-pf directives in IIFE's to prevent access globally and avoid name/function conflicts.

**Comment by dgutride** [comment]
Directives should be namespaced already - I think a pass through to make sure there are no named functions defined globally would be a good initial pass, too.

**Comment by jeff-phillips-18** [comment]
This has been completed in A-PF 4
