### ISSUE TITLE
pfListView: current item not available in <list-expanded-content>?

### ISSUE THREAD

**Issue by lorthirk** [patternfly/angular-patternfly#338]
Hello all. I'm implementing a list using pfListView, and I'd like to gather some informations about the current item to be shown there:

```
<div pf-list-view items="ctrl.packageItems" config="ctrl.packagesListViewConfig" custom-scope="ctrl">
    <div class="list-view-pf-left">
        <span class="fa fa-2x" ng-class="item.icon"></span>
    </div>
    <div class="list-view-pf-description">
        <div class="list-group-item-heading">
            {{:: item.description }}
        </div>
        <div class="list-group-item-text">
            {{:: item.version }}
        </div>
    </div>
    <list-expanded-content ng-init="currentItem = item">
        <ul class="list-group">
            <li class="list-group-item" ng-repeat="childPackage in item.childrenPackages">
                <span style="width: 50%; display: inline-block">
                        {{:: currentItem.childPackage.description }}
                    </span>
                <span>
                        {{:: currentItem.childPackage.version }}
                    </span>
            </li>
        </ul>
    </list-expanded-content>
</div>
```

But it seems that `item` is not defined inside the <list-expanded-content> scope. Am I missing something, or it needs to be implemented?

**Comment by dgutride** [comment]
@lorthirk - we took a look at this and were able to repro the issue with the current example.  Can you change your example to use $parent.currentItem.childPackage.description (and so on...) when in the list-expanded-content?  I'll update the documentation once I hear back from you.

**Comment by lorthirk** [comment]
@dgutride I tried but still no joy; I tried to use both `$parent.currentItem.childPackage.description` and `$parent.item.childPackage.description` removing the `ng-init` in the `<list-expanded-content>`.

Moreover, I read online ([here](http://angular-tips.com/blog/2014/03/transclusion-and-scopes/), for example) that a transcluded directive scope inherits directly from the controller's scope and not from the directive's one. Could this be the reason?

**Comment by jeff-phillips-18** [comment]
@lorthirk Try changing the ng-if in your html to ng-if="currentItem = $parent.item". I believe that will do the trick.

**Comment by jeff-phillips-18** [comment]
@lorthirk Try changing the ng-if in your html to ng-if="currentItem = $parent.item". I believe that will do the trick.

**Comment by lorthirk** [comment]
@jeff-phillips-18 I guess you mean the `ng-init`, not the `ng-if`. And indeed, it works perfectly that way. Thanks!

**Comment by jeff-phillips-18** [comment]
Yes, ng-init 😊   Need more ☕️   
Glad it is working for you now.
