### ISSUE TITLE
pfVerticalNavigation integration with angular-ui-router

### ISSUE THREAD

**Issue by lorthirk** [patternfly/angular-patternfly#342]
Hello,

I'm using Patternfly in an application I started to develop, and I noticed that `pfVerticalNavigation` uses the `location` service to follow the `href` attribute of the items.

I had a brief look at `pfVerticalNavigation` and it should be quite easy to modify the directive so that an item accepts a `uiSref` parameter and, if populated, it makes the directive use the `$state` service from [angular-ui-router](https://github.com/angular-ui/ui-router) to perform the navigation. Additional tests could verify that `$state` is injected properly in the directive (I would not declare a depencency from Patternfly to the `ui.router` module since this should be an optional feature) if `uiSref` is being used, and that only one between the `href` and the `uiSref` parameters are populated for a given item.

What do you think? Would you be interested in such contribution?

**Comment by jeff-phillips-18** [comment]
Sounds like a great idea to me @lorthirk

**Comment by lorthirk** [comment]
Cool. I'll start to work on that! 😄

**Comment by lorthirk** [comment]
Me and @MattiaDalBen are working on the implementation, and we have a doubt on the unit test dependencies. Specifically, to implement proper testing, we would need both [angular-ui-router](https://github.com/angular-ui/ui-router) and [jasmine-jquery](https://github.com/velesin/jasmine-jquery) as dependencies. Are you ok in getting them as devDependencies in Bower, since they're only required for testing?

**Comment by jeff-phillips-18** [comment]
I think it's ok to add the angular-ui-router as a dev dependency.

**Comment by lorthirk** [comment]
I think we can close this issue since the PR has been merged and released with 3.15.0.

**Comment by jeffbaier** [comment]
Will this work with the 1.0.0 version of UI-Router? They are currently on 1.0.0-beta.3, a final release should be coming soon. I would be interested in upgrading when it does get released. But I'll be stuck on 0.3.2 if this pfVerticalNavigation doesn't support it.

**Comment by lorthirk** [comment]
is there a list of breaking changes for 1.0?

**Comment by jeffbaier** [comment]
https://ui-router.github.io/guide/ng1/migrate-to-1_0

Also according to their blog -

> Angular 1
UI-Router 1.0 for Angular 1 is looking pretty solid. We recommend users upgrade to beta.3 immediately.

**Comment by lorthirk** [comment]
According to the [breaking changes notes](https://ui-router.github.io/guide/ng1/migrate-to-1_0#breaking-changes) there should be nothing stopping you to upgrade to 1.0.0. I also upgraded my local repo of Angular Patternfly to include UI Router 1.0.0-beta4 and, with some minor adjustments I'm going to propose with PR #355, all the unit tests are passing.
