### ISSUE TITLE
upgrade to lodash 4.x

### ISSUE THREAD

**Issue by jwforres** [patternfly/angular-patternfly#346]
There are a number of new methods available in lodash in the 4.x stream, however there are breaking changes between lodash 3.x and 4.x.  Currently angular-patternfly requires the 3.x version which prevents applications that use angular-patternfly from upgrading.

Would like to see investigation into upgrading the lodash version in the next major angular-patternfly release if possible.  Another option would be removing the dependency from angular-patternfly but I don't know how much you are depending on it today.

**Comment by dtaylor113** [comment]
Hi, just noticed we have this in our backlog:

"Remove Lodash as a required dependency in Angular-Patternfly"
https://patternfly.atlassian.net/browse/PTNFLY-1711

**Comment by benjaminapetersen** [comment]
A possible solution until then, lodash has a [_.noConflict()](https://lodash.com/docs/4.17.2#noConflict), like jQuery, that you could use to isolate patternfly usage of lodash & insulate patternfly consumers from the dependency lock-in.

**Comment by dtaylor113** [comment]
In angular-patternfly v4.x we upgraded to lodash 4.x.  I do not believe there are any plans to upgrade lodash in angular-patternfly 3.x.  Please reopen if you have a need to upgrade to lodash 4.x in angular-patternfly v3.x codebase.  -thanks
