### ISSUE TITLE
Items in an expansion list view that have disabled expansion are ill aligned.

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/angular-patternfly#368]
If an item in a list view has the disableRowExpansion flag set, the columns for that row get mis-aligned:

![image](https://cloud.githubusercontent.com/assets/11633780/21056420/897d9690-be03-11e6-9af2-232ed4173600.png)

**Comment by jeff-phillips-18** [comment]
Mistake is in application code. Closing.

**Comment by dtaylor113** [comment]
This appears to have been fixed via PR #370
