### ISSUE TITLE
pfToolbar: current view not sticking after hitting enter on filter value

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/angular-patternfly#385]
Reproducible at:

https://www.patternfly.org/angular-patternfly/#/api/patternfly.toolbars.directive:pfToolbar#example_demo

1. In toolbar, click on 'card view' icon on far right
2. In Name filter input field enter 'Frank' and hit [Enter]
3. Items are filtered to 'Frank', but view switches back to List view

I've debugged into this, cannot figure out why after hitting [Enter] key:

`Line 451 in src/toolbars/toolbar-directive.js "$scope.viewSelected = function (viewId)" `

...is called with the 'List View', even though the last view was 'Card View'

Note:
- Adding a filter via dropdown (Birth Month) doesn't result in switching back to List View; Card View remains current
- This also occurs in the a-pf 1.5 toolbar/filter components.

**Comment by jglogan** [comment]
I see the same problem.  It appears that the keypress in the filter input field is causing a click event that gets handled by ng-click handler of the view selection HTML for the toolbar.

If I make the following change to the keypress handler in the pfFilterFields directive, things appear to work more sensibly.

```
      scope.onValueKeyPress = function (keyEvent) {
        if (keyEvent.which === 13) {
          keyEvent.preventDefault();   // ADDED THIS LINE
          scope.addFilterFn(scope.currentField, scope.config.currentValue);
          scope.config.currentValue = undefined;
        }
      };
```
