### ISSUE TITLE
API documentation is not available

### ISSUE THREAD

**Issue by rhwood** [patternfly/angular-patternfly#397]
http://angular-patternfly.rhcloud.com/#/api/ has been returning a 503 error for a couple of days now.

**Comment by jeff-phillips-18** [comment]
Location has changed to http://angular-patternfly.rhcloud.com/#/api (Readme has been updated)

**Comment by jeff-phillips-18** [comment]
Sorry the new location is:

http://www.patternfly.org/angular-patternfly/#/api/

the readme file needs to be updated.
