### ISSUE TITLE
Reference Error:  continueEvent is not defined on users double click disabled row of list-view

### ISSUE THREAD

**Issue by dabeng** [patternfly/angular-patternfly#404]
![screenshot from 2017-02-10 10-50-01](https://cloud.githubusercontent.com/assets/5689075/22815682/8bbbad84-ef22-11e6-969d-73223d10cf58.png)

**Comment by dtaylor113** [comment]
Hi, I can't reproduce this.  Went to: http://www.patternfly.org/pattern-library/content-views/list-view/#/code/angular, checked '[x] Double Click', double-clicking on rows and I do not see any errors in the console.

**Comment by dtaylor113** [comment]
Closing.  Please re-open if this is still an issue.
