### ISSUE TITLE
aggregate status cards lost some pictures

### ISSUE THREAD

**Issue by dabeng** [patternfly/angular-patternfly#405]
![screenshot from 2017-02-10 13-54-39](https://cloud.githubusercontent.com/assets/5689075/22815764/5a86bee2-ef23-11e6-844d-fb9f67e479c5.png)

**Comment by dtaylor113** [comment]
This seems to have been a transient issue.  I see the images in angular-patternfly v3.x and v4.x.
![image](https://cloud.githubusercontent.com/assets/12733153/25198203/c461ca56-2514-11e7-9d6c-dc0b71fe8cbe.png)
