### ISSUE TITLE
[4.0] New pf-select component does not work with ng-model and ng-options

### ISSUE THREAD

**Issue by jjlangholtz** [patternfly/angular-patternfly#408]
Lots of existing code relies on `pf-select` to work with `ng-options` expressions. Are there any plans to add support for this with the component version?

**Comment by jeff-phillips-18** [comment]
@jjlangholtz Currently there are no plans to add support for ng-options in the 4.0 version. Would you be interested in contributing this support? If not, we can add a story to the backlog and it will be prioritized accordingly.
