### ISSUE TITLE
Chart is flickering when updating data

### ISSUE THREAD

**Issue by vitorsilvalima** [patternfly/angular-patternfly#409]
Hi guys, I`m using the Sparkline directive and it flickers when I update the data. I think this is happening because I saw that the implementation generates a new chart every time the data changes. 

To solve that problem, instead of generating a new chart, we should use the load() API of the C3.js library. 

This is the implementation now:

scope.$watch('config', function () {
          $timeout(function () {
            // store the chart object
            var chart;
            //generate c3 chart data
            var chartData = scope.config;
            if (chartData) {
              chartData.bindto = '#' + attrs.id;
              chart = c3.generate(chartData);
              if (scope.getChartCallback) {
                scope.getChartCallback(chart);
              }
            }
          });
        }, true);

**Comment by vitorsilvalima** [comment]
I fixed it by creating a flag that checks if the chart was already generated. If the chart was already generated, it only needs to update( load() API)  the chart with the new date as show below: 

 // store the chart object
        var chart;
        var created = false;
        scope.$watch('config', function () {
          $timeout(function () {
            //generate c3 chart data
            var chartData = scope.config;
            if (chartData && !created) {
              created = true;
              chartData.bindto = '#' + attrs.id;
              chart = c3.generate(chartData);
              if (scope.getChartCallback) {
                scope.getChartCallback(chart);
              }
            }else{
              chart.load(scope.config.data);
        
            }

          });
        }, true);

**Comment by ErnieAllen** [comment]
This solution also solves the problem of charts leaking memory each time the chart's data is updated.
In Chrome the leak leads to a crashed tab. In FF is just appears to slow down until the entire browser is unusable.

**Comment by vitorsilvalima** [comment]
So, can I send a pull request? I`m pretty happy with the results in my apps.

**Comment by vitorsilvalima** [comment]
I think this can be closed now.
