### ISSUE TITLE
pfCard Ng-Docs issues

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/angular-patternfly#42]
1 - The Parameters show that the "showTopBorder" is false by default, but the Demo, shows the border.  If it isn't the default, i'd suggest it's not shown.  Can the demo be enhanced to allow the option to show/hide the border?
2 - Typo here ... "subtTtle"

<img width="546" alt="pfcardtype" src="https://cloud.githubusercontent.com/assets/12504403/9448585/6d360920-4a6b-11e5-8884-349f271a7090.png">

**Comment by erundle** [comment]
Addressed in https://github.com/patternfly/angular-patternfly/pull/44
