### ISSUE TITLE
The pf-notification-drawer could use a built-in dismiss action

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#421]
Using the "bell" in the top nav makes sense for opening a notification drawer, but seems a bit odd to also use as the closing action.  I'm curious if a "dismiss" action could be added at the top near the `<<` icon, or provide a `footer-include` attribute (not `notification-footer`, but one for the drawer itself) that would allow for a location to place a button to hook up a "dismiss" to toggle the `hideDrawer` attrib.  

<img width="328" alt="screen shot 2017-02-16 at 10 31 42 pm" src="https://cloud.githubusercontent.com/assets/280512/23051700/ff1ce8f8-f498-11e6-8b80-414e0a79fbef.png">
<img width="689" alt="screen shot 2017-02-16 at 10 31 50 pm" src="https://cloud.githubusercontent.com/assets/280512/23051699/ff1bc63a-f498-11e6-962b-220edaf2e80e.png">

**Comment by jeff-phillips-18** [comment]
This is more of a Patternfly design pattern question. I agree with you though, I have often found myself looking for a close button.

@LHinson Could this be brought up in a patternfly design discussion?

**Comment by benjaminapetersen** [comment]
Yup, would be great to iron that one out in a generic way that could be consistent across products.  Its like a natural impulse to play with the open/close immediately, so not being certain about the location of the close button is a little unsettling.

**Comment by benjaminapetersen** [comment]
@LHinson or anyone who may know, is the notification drawer used on any other RH products w/a solution for this button already implemented? Would be interesting to see as we are integrating the drawer this sprint in openshift.
