### ISSUE TITLE
Provide an attribute to opt-in to the accordion within pf-notification-drawer

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#432]
The accordion is a nice feature when needed, but it would also be handy to be able to have a list of simple events.  My use case may not need the rollup.  This could be an attribute, or simply based on the structure of the `notificationGroups` object passed.  If it is a simple array, skip the `pf-fixed-accordion`.

**Comment by benjaminapetersen** [comment]
If not an opt in to accordion, it could work to still use the headings, just not collapsible. That may be a good way to keep the data structure the same & just toggle the presentation.

**Comment by jeff-phillips-18** [comment]
Fixed vai #526
