### ISSUE TITLE
listview config for actionButton class not displaying in some cases

### ISSUE THREAD

**Issue by derekmwright** [patternfly/angular-patternfly#433]
When trying to pass a different class for a listview action button like `btn-danger` the default class of `btn-default` takes precedent and renders as such. `btn-primary` however seems to override `btn-default` so this seems to have gone unnoticed. I will submit a PR that fixes this by doing `btn {{actionButton.class = actionButton.class || 'btn-default'}}` in the template. Tests for the fix are included as well.

**Comment by dtaylor113** [comment]
Fixed via #455
