### ISSUE TITLE
What to do if too many headings in pf-notification-drawer

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#436]
I came across this when experimenting with different ways to process data into the `pf-notification-drawer`.  Once you hit a certain number of headings, there is no way to scroll & get to the headings too low in the drawer (the only scrollers are within open headings):

![screen shot 2017-03-13 at 4 34 15 pm](https://cloud.githubusercontent.com/assets/280512/23874265/4e7f06b2-080b-11e7-9f14-17d87bce84a1.png)

You can see additional headings at the very bottom.

**Comment by benjaminapetersen** [comment]
@jeff-phillips-18 wonder if this one should be labelled `bug` w/a severity.  I don't think there is a workaround with scrolling suppressed.  On mobile the issue would definitely be more severe as you would only see a few headings & most would be below the fold/unreachable.

It would not affect what I am currently doing in the web console, but it does seem to be a reasonable use of the drawer.

**Comment by jeff-phillips-18** [comment]
@benjaminapetersen I can agree with that. Thanks for the feedback.

**Comment by serenamarie125** [comment]
@jeff-phillips-18 @beanh66 This use case isn't covered by the design pattern.  The initial intent of the notification drawer was to focus on Tasks & Events accordions.  At the time of design, the use case was to have <5 accordions, and the current design is based on that.

If we determine that we have a use case for more than that, we would need to update the design first, and then come back and implement.

IMO, this is an enhancement, other we may want to be more explicit in our design documentation.

**Comment by beanh66** [comment]
@jeff-phillips-18 per the explanation above, I'm going to close this issue. We can reopen if this use case surfaces at all.
