### ISSUE TITLE
Side scrollers can appear on items in the pf-notification-drawer

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#437]
Here I have the same `notification-body.html` template as provided in the example, but ended up generating items with side to side scrollbars:

![screen shot 2017-03-13 at 4 39 22 pm](https://cloud.githubusercontent.com/assets/280512/23874345/a0572438-080b-11e7-923f-9bfafe759114.png)

**Comment by benjaminapetersen** [comment]
Quick update, after the last batch of updates to the drawer:

![screen shot 2017-08-01 at 12 11 13 pm](https://user-images.githubusercontent.com/280512/28835195-94efe876-76b2-11e7-8d60-af70184e6ec0.png)

This one does remain. Not sure if there is anything that can be done in the drawer, actually.  Forcing word-wrap rules would create a bunch of quirks.  Might need to be resolved on a case-by-case basis in user code.

**Comment by jeff-phillips-18** [comment]
Indeed I believe this would need to be handle by the body content in the application. I see nothing that could be done in the drawer component that would solve this.
