### ISSUE TITLE
pfTableView with toolbar - inconsistent with design

### ISSUE THREAD

**Issue by alexkieling** [patternfly/angular-patternfly#449]
pfTableView with toolbar is inconsistent with PatternFly Data Tables design:
https://www.patternfly.org/pattern-library/widgets/#data-tables

Issues:
- "table-view-pf-toolbar" CSS class is missing in toolbar.
- The following CSS rules from `angular-datatables.css` are adding a top margin to the table:
```
table.dataTable,
table.dataTable.no-footer{
    margin: 1rem 0;
    width: 100% !important;
    border-top: 1px solid #DDDDDD;;
    border-bottom: 1px solid #DDDDDD;
}
```
- There is too much padding to the left of the toolbar action buttons.

![screenshot1](https://cloud.githubusercontent.com/assets/1910095/25136238/ce6980f6-242a-11e7-8dcc-ba9c5cd11b59.png)

**Comment by alexkieling** [comment]
Two more issues:

- The following CSS rules from `angular-datatables.css` are adding a top margin to the table:
```
table.dataTable,
table.dataTable.no-footer{
    margin: 1rem 0;
    width: 100% !important;
    border-top: 1px solid #DDDDDD;;
    border-bottom: 1px solid #DDDDDD;
}
```
- There is too much padding to the left of the toolbar action buttons.

![screenshot1](https://cloud.githubusercontent.com/assets/1910095/25136238/ce6980f6-242a-11e7-8dcc-ba9c5cd11b59.png)

**Comment by dtaylor113** [comment]
> The following CSS rules from angular-datatables.css are adding a top margin to the table

This is in the 'angular-datatables' dependency and pfTableView ng-doc examples seem to render ok (in PR #452 ).   If it does not render as you want in your app, you can overwrite `table.dataTable.no-footer` in your application.
Thanks,
- Dave
