### ISSUE TITLE
Support for SASS-based workflow

### ISSUE THREAD

**Issue by skateman** [patternfly/angular-patternfly#473]
Hi guys,

I'm trying to catch up with this new version and I'm a bit scared that you have included the stylesheets into this repo. This causes a lot of problems with the LESS->SASS conversion that was working for versions 1-2-3. Is there any reason behind not having them separately as before?

**Comment by martinpovolny** [comment]
ping @jeff-phillips-18?

Can we hope to get the packages separately as before?

It makes no sense for us to invest in LESS esp. if/when patternly 5 is going to use SASS.

**Comment by jeff-phillips-18** [comment]
What kinds of problems does this cause? The only real difference is that we distribute the less files now which I would think you could ignore.

**Comment by skateman** [comment]
@jeff-phillips-18 aren't those LESS files bundled into the components? What stylesheets should we use then? Will be there a non-angular (patternfly) version with the CSS files as before?

**Comment by jeff-phillips-18** [comment]
The angular patternfly specific css can be found in dist/styles/angular-patternfly.css 

This should be similar to what was in 3.x.  Changing to less internally allows the css to be generated with values from patternfly variables. If those values are an issue now, then the were likely an issue before and applications were overriding them.
