### ISSUE TITLE
Rename step.nextTitle for pf-wizard

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#492]
Original comment [this issue](https://github.com/openshift/origin-web-console/issues/1707#issuecomment-308540584) in the openshift web console.

It would be helpful to rename this:

```javascript
step.nextTitle = 'Foo';
```
to something like:

```javascript 
ctrl.nextButtonText = 'Foo';
```
Perhaps something less verbose but more clear.  "Next Title" seems to imply it will be the title for the next step panel, when in fact, it is the text on the button in this panel, but clicking it will progress the user to the next step in the wizard.  

Open to thoughts, I just find this name a bit misleading.

**Comment by jeff-phillips-18** [comment]
I'm not certain changing this at this time is warranted as it will break any previous uses. You can still use ctrl.nextButtonText and in the html use next-title="$ctrl.nextButtonText".

If you feel differently, please re-open.
