### ISSUE TITLE
pfTableView:  Need to be able to not show checkboxes

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/angular-patternfly#494]
Need to add a 'showCheckboxes' Boolean attribute to the config object (default is 'true') which will control showing/hiding the initial column of checkboxes used for row selection.

**Comment by mechevarria** [comment]
In other words, in the following:

https://github.com/patternfly/angular-patternfly/blob/master/src/table/tableview/table-view.component.js

```
ctrl.defaultDtOptions = {
    autoWidth: false,
    destroy: true,
    order: [[1, "asc"]],
    dom: "t",
    select: {
        selector: 'td:first-child input[type="checkbox"]',
        style: 'multi'
    }
};
```

It would good to have the ability to set `select: false`
Trying to override that setting in the current implementation doesn't currently work

**Comment by serenamarie125** [comment]
Being tracked in JIRA: https://patternfly.atlassian.net/browse/OSUX-27
