### ISSUE TITLE
pfTableView: update pagination controls to latest patternfly design

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/angular-patternfly#495]
http://www.patternfly.org/pattern-library/content-views/table-view/#/code

https://www.patternfly.org/pattern-library/navigation/pagination/

**Comment by serenamarie125** [comment]
https://patternfly.atlassian.net/browse/OSUX-25

**Comment by LHinson** [comment]
Hi all, passing along the work done on pagination thus far in the PatternFly space per @serenamarie125 request. 

Pagination testing results: https://blog.patternfly.org/pagination-in-patternfly-second-round-cafeteria-testing/

Current prototypes are here (please note you need to connect via viscosity to access : 
* http://file.rdu.redhat.com/~mstevens/paging/opt1.html
* http://file.rdu.redhat.com/~mstevens/paging/opt2.html (with sticky footer). 

Let me know if you  have any comments or questions!

**Comment by dtaylor113** [comment]
Hi @LHinson, pls send info. on how I can get a viscosity account, thanks!  These are labeled prototypes, so does that mean I shouldn't use what is in the PF design docs?

**Comment by dtaylor113** [comment]
> Current prototypes are here (please note you need to connect via viscosity to access

@LHinson, could you pls send me instructions on how to get a viscosity account, or just simply send me a few screenshots :-)  I've put up an angular-pf PR which uses the current pagination designs.  https://github.com/patternfly/angular-patternfly/pull/514
Seems logical to get an initial version up, then we can easily change it after these prototypes have been hammered out.

**Comment by dtaylor113** [comment]
Hi @LHinson, I recently updated the pagination controls for List, Card, and Table views in angular-patternfly.  The match what is currently in pf design.   I'm not sure if that work addresses this issue or not -not sure about the prototypes or survey results?

**Comment by dtaylor113** [comment]
Hi @LHinson,
I'm going to close this issue because I believe the pagination controls do match what is currently published PF designs.  Please open another issue if new designs become available.
Thanks,
Dave
