### ISSUE TITLE
Border used in Expanded List View should be grey

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/angular-patternfly#496]
Current implementation of expanded list view ( http://www.patternfly.org/angular-patternfly/#/api/patternfly.views.component:pfListView ) 

<img width="1000" alt="screen shot 2017-06-15 at 1 39 31 pm" src="https://user-images.githubusercontent.com/12504403/27194320-1cfee9e0-51d0-11e7-8ae7-4846e9cf6085.png">

should be grey rather than blue.  @andresgalante could you add a link to the proper styling in PF core for reference ?

**Comment by jeff-phillips-18** [comment]
@serenamarie125 The implementation in Patternfly is blue. This issue should be filed there as those changes would be picked up automatically in the angular-patternfly implementation.

**Comment by jeff-phillips-18** [comment]
See https://github.com/patternfly/patternfly/issues/653

**Comment by beanh66** [comment]
@jeff-phillips-18 Has this issue been resolved in PF core? I thought @andresgalante may have done some work around this issue. Wondering if we can close this or change the Priority. Thanks!

**Comment by jeff-phillips-18** [comment]
@beanh66 Yes but it has not yet released so it has not been verified here.

**Comment by dtaylor113** [comment]
Looks like expanded rows now have a grey border:
![image](https://user-images.githubusercontent.com/12733153/29623948-e846a128-87f5-11e7-825b-739112432d6f.png)
