### ISSUE TITLE
npm install angular-patternfly doesn't bring in all dependencies for version >= 4.0.0

### ISSUE THREAD

**Issue by aptmac** [patternfly/angular-patternfly#516]
Hi!

**Description:**
- When trying to update from version 3.* to version 4.1.0 via my application's package.json, not all components of angular-patternfly are imported
- angular-patternfly gets set up in app/node_modules/angular-patternfly, but the only package found in angular-patternfly/node_modules is moment

I have been able to get angular-pf 4.* working, the steps required are just a bit longer:
1. run npm install for my app
2. move into app/node_modules/angular-patternfly
3. perform another npm install (which will set up angular-pf as expected)

Reproduced for angular-patternfly 4.0.0 & 4.1.0.
This issue wasn't present for angular-patternfly 3.23.* or 3.25.*

Can anyone else reproduce this? Or perhaps I'm missing a step when importing? The line in my package.json at the moment is:
`"angular-patternfly": "^4.1.0",`

**Comment by aptmac** [comment]
From a bit of digging, it looks like this may have been introduced when the build package was updated [0]? 

For reference, this is what my node_modules/angular-patternfly looked like in v3.23.3
![version 3.23.0](https://cdn.pbrd.co/images/GAV0a8S.png)

And this is what it looks like in 4.1.1
![version 4.1.1](https://cdn.pbrd.co/images/GAV0VMa.png)

[0] https://github.com/patternfly/angular-patternfly/pull/475

**Comment by jeff-phillips-18** [comment]
I tried this with a new directory containing package.json:
{
  "name": "jeff",
  "version": "1.0.0",
  "dependencies": {
    "angular-patternfly": "^4.1.0"
  }
}

This resulted in:
![image](https://user-images.githubusercontent.com/11633780/28573442-ab0f071c-7118-11e7-930c-cb1e77f4ed9a.png)

Which seems correct. Please re-open if you still see the issue.

**Comment by aptmac** [comment]
Hi @jeff-phillips-18, 

Thanks for the comment and looking into the problem I was seeing. I see now that my confusion is that the dependencies in version 3.* are placed under

` project/node_modules/angular-patternfly/node_modules/[angular, angular-animate ..., patternfly], `

but in version 4.* they're found in 

`project/node_modules/[angular, angular-animate ..., patternfly]`

The errors I was seeing was because my aliases were broken, and the angular-patternfly README currently references the old paths. For example, the jquery alias of 
`alias: { "jquery": "angular-patternfly/node_modules/patternfly/node_modules/jquery" }` 
is now incorrect because jquery is not located under angular-patternfly anymore.

**Comment by jeff-phillips-18** [comment]
thanks @aptmac we will update the README.
