### ISSUE TITLE
3.x Notification panel-body renders notification footer actions invisible

### ISSUE THREAD

**Issue by AllenBW** [patternfly/angular-patternfly#518]
Version: 3.25.0

Upon initially loading the page ya see this, no clear or clear all actions:
<img width="1920" alt="screen shot 2017-07-12 at 2 03 19 pm" src="https://user-images.githubusercontent.com/6640236/28132564-37d33bea-670b-11e7-95b3-21bf2b77e4c7.png">

After modifying the size of the viewport these buttons are revealed: 
<img width="1323" alt="screen shot 2017-07-12 at 2 03 28 pm" src="https://user-images.githubusercontent.com/6640236/28132597-4e506820-670b-11e7-9508-341a31262bda.png">

Issue is with the `max-height` of the `panel-body` div, it initially calculates a number too high and pushes the actions outta da view

<img width="1025" alt="screen shot 2017-07-12 at 2 07 34 pm" src="https://user-images.githubusercontent.com/6640236/28132699-8d934b2e-670b-11e7-83ba-c63077915353.png">

**Comment by beanh66** [comment]
Assigning to @jeff-phillips-18 as this may be taken care of already with the Notification Drawer updates that are in progress.

**Comment by jeff-phillips-18** [comment]
@AllenBW  This will be fixed in 4.x via #548 

Please let me know if this needs to be backported.

**Comment by AllenBW** [comment]
@jeff-phillips-18 awesomeeeeee!!!! <3 <3 yes please backported

**Comment by jeff-phillips-18** [comment]
I cannot reproduce this in 3.x latest.

**Comment by jeff-phillips-18** [comment]
Downgrading the priority since this is not (at least easily) reproduced and is against 3.x

**Comment by dtaylor113** [comment]
@AllenBW, hi, is this still an issue for you?  -thanks

**Comment by AllenBW** [comment]
@dtaylor113 nope! we're all good for the time being, thanks for touching base! <3
