### ISSUE TITLE
In pf-wizard there's no way to conditionally add a step 

### ISSUE THREAD

**Issue by alexcreasy** [patternfly/angular-patternfly#519]
There doesn't seem to be a way to add a step conditionally based on a boolean property. I've tried using an ng-if on the pf-wizard-step tag but that doesn't work, the step still appears.

Using ng-if on pf-wizard-substep tags does work as expected. I'm currently using this as a work around, but it would be really helpful if this could be made to work for top level steps. It doesn't have to use ng-if, any custom property enabling this behaviour would work fine.

This is really useful for me as it allows reuse of the same wizard for multiple contexts. In certain contexts you may already know a certain amount of information that you don't then need to ask the user to supply.

For example a top level button vs a list view action button. If the top level button is selected the user needs to chose which item to apply the wizard to in the first step. If the user clicks the action button in the table row, this has already been decided and the user does not need to select which item they need to apply it to.

**Comment by jeff-phillips-18** [comment]
Setting wzDisabled parameter to true for a pf-wizard-step will 'hide' the step.

The documentation for this parameter is incorrect.
