### ISSUE TITLE
pfFilter: RFE - Multi-dropdown filter, filterAlias, input typeahead

### ISSUE THREAD

**Issue by AllenBW** [patternfly/angular-patternfly#521]
As per: https://github.com/ManageIQ/manageiq-ui-service/pull/840#issuecomment-315496383 being able to display a second dropdown that further breaks up filter content grouping would be aweeeesommeee

ALSO if [filter fields](https://github.com/patternfly/angular-patternfly/blob/master/src/filters/filter-component.js#L29-L35) supported value aliases or in other words an additional filter value field available for passing a value around, for when the consumer of the filter requires drastically different formatting than what is pleasant for users to view

ALSO if filter inputs were typeaheads

Apologies if this comes across as needy, sometimes a fella just wanta extra special filtering fun! 🌮 💃 

ps: mostly ordered by level of how awesome each would be <3

pss:  the highest impact easiest win here would be `filterAlias` could temporarily alienate need for multi filter dropdowns

**Comment by AllenBW** [comment]
If the alias thing sounds like something that ya might be keen on adding I can throw a wip pr out there for review.

**Comment by serenamarie125** [comment]
@jeff-phillips-18 have you done anything similar to this in the past?  Essentially SUI needs to filter by "tag", which means two ui-select components.

**Comment by jeff-phillips-18** [comment]
@serenamarie125 I don't recall doing this before, but I can see the need and would welcome the PR

**Comment by chriskacerguis** [comment]
FYI - @AllenBW is going to do this, and we are tracking this here: https://www.pivotaltracker.com/story/show/148997399

**Comment by AllenBW** [comment]
Oh my priority 1 @jeff-phillips-18  what does that mean!!?? 😟
