### ISSUE TITLE
"patternfly" & "c3ChartDefaults" undefined when running Angular Patternfly standalone

### ISSUE THREAD

**Issue by cdcabrera** [patternfly/angular-patternfly#534]
Unable to run Angular Patternfly JS as a standalone script reference without including core Patternfly JS because of of multiple references and calls to the global ```patternfly``` object and subsequent method call to ```c3ChartDefaults``` ... 

```javascript
patternfly.c3ChartDefaults()
```

Purposing a quick fix within ```c3-chart-defaults.js``` similar to...
```javascript
(function (window, patternfly) {
  'use strict';

  window.patternfly = patternfly || {};
  window.patternfly.c3ChartDefaults = patternfly.c3ChartDefaults || function(){ console.error('patternfly.c3ChartDefaults unavailable.\nhttps://github.com/patternfly/angular-patternfly'); return{} };

  var patternflyDefaults = patternfly.c3ChartDefaults();
```

**Comment by dtaylor113** [comment]
:+1:

**Comment by dtaylor113** [comment]
Sorry, I know I gave this a :+1: earlier, but why is this necessary?  Doesn't a-pf's npm/bower pull in core patternfly?  Doesn't our karma.conf pull in the required pf scripts?

**Comment by cdcabrera** [comment]
Redirected towards PR #538 ...

**Comment by beanh66** [comment]
@cdcabrera Can we close this or is the issue still standing?

**Comment by cdcabrera** [comment]
@beanh66 we can close then re-open as necessary
