### ISSUE TITLE
Error on heatmap

### ISSUE THREAD

**Issue by serggb** [patternfly/angular-patternfly#546]
HI,

I'm trying use a heatmap. I us like this:

`<pf-heatmap id="id" data="data" max-block-size="20"
						show-legend="false" heatmap-color-pattern="heatmapColorPattern"
						thresholds="thresholds" range-on-hover="false"></pf-heatmap>`

On my script.js:

`$http.get('/monitorRest').success(function(data)` {
	$scope.data= data.monitor;
	$scope.total= data.totalCounter;
	$scope.service= data.serviceCounter;
	$scope.warning= data.warningCounter;
	$scope.error= data.errorCounter;
  });`

The error in browser:

`angular.js:14199 TypeError: Cannot read property 'length' of undefined
    at setSizes (angular-patternfly.js:4548)
    at angular.module.component.controller.ctrl.$postLink (angular-patternfly.js:4755)
    at angular.js:9564
    at forEach (angular.js:333)
    at nodeLinkFn (angular.js:9561)
    at angular.js:9886
    at processQueue (angular.js:16696)
    at angular.js:16712
    at Scope.$eval (angular.js:17994)
    at Scope.$digest (angular.js:17808)
(anonymous) @ angular.js:14199
(anonymous) @ angular.js:10707
processQueue @ angular.js:16704
(anonymous) @ angular.js:16712
$eval @ angular.js:17994
$digest @ angular.js:17808
$apply @ angular.js:18102
bootstrapApply @ angular.js:1812
invoke @ angular.js:4771
doBootstrap @ angular.js:1810
bootstrap @ angular.js:1830
angularInit @ angular.js:1715
(anonymous) @ angular.js:32616
mightThrow @ jquery.js:3583
process @ jquery.js:3651
angular.js:14199 Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.11/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:68
    at Scope.$digest (angular.js:17874)
    at Scope.$apply (angular.js:18102)
    at done (angular.js:12082)
    at completeRequest (angular.js:12291)
    at XMLHttpRequest.requestLoaded (angular.js:12219)
(anonymous) @ angular.js:14199
(anonymous) @ angular.js:10707
$apply @ angular.js:18104
done @ angular.js:12082
completeRequest @ angular.js:12291
requestLoaded @ angular.js:12219
angular.js:68 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.11/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:68
    at Scope.$digest (angular.js:17874)
    at Scope.$apply (angular.js:18102)
    at done (angular.js:12082)
    at completeRequest (angular.js:12291)
    at XMLHttpRequest.requestLoaded (angular.js:12219)
(anonymous) @ angular.js:68
$digest @ angular.js:17874
$apply @ angular.js:18102
done @ angular.js:12082
completeRequest @ angular.js:12291
requestLoaded @ angular.js:12219
angular.js:14199 Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.11/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:68
    at Scope.$digest (angular.js:17874)
    at Scope.$apply (angular.js:18102)
    at angular.js:19950
    at completeOutstandingRequest (angular.js:6045)
    at angular.js:6324
(anonymous) @ angular.js:14199
(anonymous) @ angular.js:10707
$apply @ angular.js:18104
(anonymous) @ angular.js:19950
completeOutstandingRequest @ angular.js:6045
(anonymous) @ angular.js:6324
angular.js:68 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.11/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:68
    at Scope.$digest (angular.js:17874)
    at Scope.$apply (angular.js:18102)
    at angular.js:19950
    at completeOutstandingRequest (angular.js:6045)
    at angular.js:6324
(anonymous) @ angular.js:68
$digest @ angular.js:17874
$apply @ angular.js:18102
(anonymous) @ angular.js:19950
completeOutstandingRequest @ angular.js:6045
(anonymous) @ angular.js:6324
angular.js:68 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.11/$rootScope/infdig?p0=10&p1=%5B%5D
    at angular.js:68
    at Scope.$digest (angular.js:17874)
    at angular.js:18033
    at completeOutstandingRequest (angular.js:6045)
    at angular.js:6324
(anonymous) @ angular.js:68
$digest @ angular.js:17874
(anonymous) @ angular.js:18033
completeOutstandingRequest @ angular.js:6045
(anonymous) @ angular.js:6324
`

The heatmap draws ok, but this error appears and the tooltips not work.

Can you help me?

Thanks

**Comment by dtaylor113** [comment]
It appears to be crashing on '$scope.data.length' where $scope.data is undefined, most likely because $scope.data is being set asynchronously after a deferred promise.  I would suggest setting $scope.data = [] initially before the promise.
Thanks,
Dave

**Comment by serggb** [comment]
Thanks, the length error is solved now, but the 10 $digest() iterations
reached error remains.

Any idea?

2017-08-03 14:54 GMT+02:00 David Taylor <notifications@github.com>:

**Comment by dtaylor113** [comment]
Hi, I would need to see the code.  Can you create a JSFiddle?
Thanks,
- Dave

**Comment by serggb** [comment]
https://jsfiddle.net/umztfcd2/5/

Thanks

2017-08-03 16:55 GMT+02:00 David Taylor <notifications@github.com>:
