### ISSUE TITLE
Notifcation Drawer requires navbar-pf-vertical, but adds an unnecessary top border

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#549]
In order to get the notification drawer to work properly, you must do:

```html
    <div class="navbar-pf-vertical">
      <notification-drawer></notification-drawer>
    </div>
```
But this will add a 2px top border that causes scrollbars to appear:

![screen shot 2017-08-03 at 3 01 52 pm](https://user-images.githubusercontent.com/280512/28938656-b6e440b6-785c-11e7-8998-e371a9ae6f2f.png)

If `navbar-pf-vertical` is required for the notification drawer to calculate its own height & position properly, it should not also add the border.

@rhamilto @jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
It doesn't require navbar-pf-vertical. It just needs styling such that it takes up the full vertical space with some margins. See http://www.patternfly.org/angular-patternfly/#/api/patternfly.notification.component:pfNotificationDrawer

> The pfNotificationDrawer has stylings pre-set from Patternfly (http://www.patternfly.org/) for use within the navbar-pf and navbar-pf-vertical containers. If neither is being used, the top and height should be set such that the drawer will take up the entire viewport vertically. For instance:
> .my-nav-container .drawer-pf {
>   height: calc(~"100vh - 46px");
>   top: 26px;
> }
> 
> Note, this should be bottom aligned with the trigger, and leave a 20px at the bottom of the viewport. 
>

**Comment by benjaminapetersen** [comment]
We found that snippet & included it, though I wonder if there is a better way to encapsulate those rules.

Aside, it may be beneficial of documentation like this had an explicit callout style [similar to what Bootstrap does](https://getbootstrap.com/css/#inputs), (since it doesn't work w/o the snippet) :

![screen shot 2017-08-03 at 5 21 17 pm](https://user-images.githubusercontent.com/280512/28944399-5a69374c-7870-11e7-9bda-cc4a638a16b2.png)

The "You must manually do this or it won't work" message pops out w/the red border/bold treatment.

**Comment by beanh66** [comment]
@benjaminapetersen Can I close this issue? Looks like Jeff resolved it, but became more of a documentation discussion. Let me know, I was just doing some cleanup work. Thanks!

**Comment by benjaminapetersen** [comment]
Can the docs call this out more clearly (see my above comment).  Currently it looks like:

<img width="1069" alt="screen shot 2018-02-01 at 11 53 07 am" src="https://user-images.githubusercontent.com/280512/35691490-916361f4-0746-11e8-8ad2-8ed812aacd8b.png">

I'd love to see some color or something to draw attention to that quirk.  Thanks!

**Comment by beanh66** [comment]
Okay thanks for posting the image @benjaminapetersen, we'll try to get that change in!

**Comment by benjaminapetersen** [comment]
Sounds good!
