### ISSUE TITLE
Date and time in the Drawer need to collapse at smaller screen sizes

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#576]
When using the provided `drawer-pf-notification-info` class with date & timestamps, the drawer struggles to display content meaningfully at smaller screen sizes. 

Initial comment on [this PR](https://github.com/openshift/origin-web-console/pull/1326#issuecomment-322923197) in origin-web-console.

Web console example:
![openshift web console 2017-08-16 19-02-08](https://user-images.githubusercontent.com/1167259/29388958-6afafa10-82b5-11e7-85d3-9eeb929a84f5.png)

Docs example, with a slightly edited message:
<img width="383" alt="screen shot 2017-08-17 at 2 49 42 pm" src="https://user-images.githubusercontent.com/280512/29428531-8ebf5832-835b-11e7-8dd8-23a1550a68c8.png">

Initial thoughts are to make them stack at a certain point.  These issues are a little fuzzy as the content inside the drawer is "user land", but still depends on Patternfly internals.

**Comment by benjaminapetersen** [comment]
@jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
So the issue is not with the date/time per se as that is custom content. The problem is that the drawer-pf-notification-info will take up as much room as it needs and whatever is left goes for the message. 

We should determine at what size these should stack. This is a core Patternfly issue.

Opened: https://github.com/patternfly/patternfly/issues/721

**Comment by benjaminapetersen** [comment]
Correct.  It seems like the kind of problem that could be solved with a `container-fluid` and nesting `row` and `column`s, if we wanted to stick with bootstrap layout language.  If not, then more clearly defining primary, secondary, tertiary content columns & formalizing the patterns that they follow as space expands/collapses.

**Comment by matthewcarleton** [comment]
This was taken care of in https://github.com/patternfly/patternfly/pull/717

The content now stacks at a wider breakpoint to avoid narrow columns of content.
