### ISSUE TITLE
At smaller screens, the Drawer expand button actually causes it to shrink

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#577]
The effect starts at more or less mobile size.  This gif should illustrate.

![2017-08-17 14 57 24](https://user-images.githubusercontent.com/280512/29428814-8b1a0686-835c-11e7-9a7f-52469cc5cde9.gif)

@jeff-phillips-18 @beanh66 

Relevant to web-console [PR 1326](https://github.com/openshift/origin-web-console/pull/1326).

**Comment by beanh66** [comment]
@benjaminapetersen I would think the expand feature would be hidden on mobile and that the drawer would take up the width of the screen actually. Oddly the other thing I notice is the arrows are facing the wrong way for expand and collapse, not sure if that's on the PF side or why that might be.

**Comment by spadgett** [comment]
@beanh66 The arrows are facing the right way, but expand is making the drawer smaller instead of bigger :)

**Comment by benjaminapetersen** [comment]
As @spadgett, the arrow does the inverse at smaller screens.  An animated-gif from [patternfly.org](http://www.patternfly.org/angular-patternfly/#/api) verifies it outside the web console:

![2017-08-17 15 17 15](https://user-images.githubusercontent.com/280512/29429663-76c4d10e-835f-11e7-8c0b-83f131461641.gif)

**Comment by benjaminapetersen** [comment]
For some reason github decided to make that gif extra large and obnoxious.  🙁

**Comment by benjaminapetersen** [comment]
This might be a separate docs issue, but I noticed as I played with the resize the notification bell (and menu area) disappears entirely:

![2017-08-17 15 25 15](https://user-images.githubusercontent.com/280512/29429931-6bd3e9dc-8360-11e7-8c02-53576fa22b62.gif)

**Comment by beanh66** [comment]
@spadgett @benjaminapetersen haha sorry, I see it now with the arrows. In general I do still think the drawer should take up the entire width of the screen and the expand feature should be hidden for mobile.

**Comment by benjaminapetersen** [comment]
@beanh66 sounds like a good solution to me!

**Comment by beanh66** [comment]
@benjaminapetersen We have a responsive design for the notification drawer that should help cover the issues you are experiencing at mobile and smaller screen sizes. You can find the design documentation at the bottom of this [page](http://www.patternfly.org/pattern-library/communication/notification-drawer/#/design) on the PF site. @matthewcarleton has this [story](https://patternfly.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=PTNFLY&view=planning&selectedIssue=PTNFLY-1461) and is currently working on the implementation in PatternFly Core and then we can work on getting it into Angular.

**Comment by matthewcarleton** [comment]
@benjaminapetersen @beanh66  hey, ya I have already addressed these issues in the work on I'm doing in core. The expand is removed on smaller screens and the drawer is full width. It should be merged soon :)

**Comment by benjaminapetersen** [comment]
@matthewcarleton awesome, look forward to pulling in those changes!

**Comment by spadgett** [comment]
https://github.com/patternfly/patternfly/pull/717
