### ISSUE TITLE
Spacing in the Trend Card example has too much space between the values & Sparkline

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/angular-patternfly#579]
Spacing is incorrect here: http://www.patternfly.org/angular-patternfly/#/api/patternfly.card.component:pfCard%20-%20Trends

![screen shot 2017-08-17 at 4 27 49 pm](https://user-images.githubusercontent.com/12504403/29432510-f9da065e-8369-11e7-8b18-41119eff925f.png)

Design can be seen here: http://www.patternfly.org/pattern-library/cards/trend-card/#/design

**Comment by jeff-phillips-18** [comment]
@serenamarie125 What is the spacing requirement? I don't see it specified by the design.

**Comment by serenamarie125** [comment]
Good question @jeff-phillips-18 let me have Jenny take a look
