### ISSUE TITLE
Support for new layout for Trend Card

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/angular-patternfly#580]
Would like an example of an alternate label placement of "Card with Single Trend" shown here
http://www.patternfly.org/angular-patternfly/#/api/patternfly.card.component:pfCard%20-%20Trends

similar to this:
<img width="395" alt="screen shot 2017-08-18 at 12 15 16 pm" src="https://user-images.githubusercontent.com/12504403/29467570-f16bdbfa-840e-11e7-89e3-c8a84a9f6cfe.png">

**Comment by dtaylor113** [comment]
The new layout is really close to the 'compact' layout:
![image](https://user-images.githubusercontent.com/12733153/29531004-8b7a35d6-8674-11e7-8787-6f8fb46c8a7f.png)

We can look at adding a config option to specify 'compact layout label placement' either 'left' or 'right'.  Would that work?

**Comment by amarie401** [comment]
I think that would be pretty efficient to do it that way

**Comment by amarie401** [comment]
Is this what you were suggesting? @dtaylor113 
With the help of @jeff-phillips-18 I was able to create this using the compact layout for the TrendsChart demo. I have not added it to the TrendsCard example as of yet.

@serenamarie125 

<img width="925" alt="screen shot 2017-08-21 at 5 43 15 pm" src="https://user-images.githubusercontent.com/20052391/29539775-5dc860fc-8699-11e7-940e-fe211bea6d0d.png">

**Comment by beanh66** [comment]
@amarie401 I know Serena is out this week but I think that looks great! FYI I just put up the design for this yesterday to be sure the "right compact" option is documented in PatternFly. I should have tagged you but here is the [design PR](https://github.com/patternfly/patternfly-design/pull/374/files)!

**Comment by amarie401** [comment]
@beanh66 awesome thank you!

**Comment by dtaylor113** [comment]
Hi @amarie401, yes, that was exactly what I was thinking.  Just please be sure that the default is 'left' when no 'compact label position' param/attribute is specified.  -Thanks!

**Comment by serenamarie125** [comment]
Yes @amarie401 this is exactly what I was hoping for :)  Thank you!
