### ISSUE TITLE
Ratio of label:input width in pf-form-group

### ISSUE THREAD

**Issue by Hyperkid123** [patternfly/angular-patternfly#582]
I noticed that the `label` and `input` width in `pf-form-group` is fixed to 2:5. This causes problems if I'm trying to display something useful on the right from the form.

![screenshot from 2017-08-21 13-59-24](https://user-images.githubusercontent.com/22619452/29518288-fbf18766-8678-11e7-9939-0daeeeebcf02.png)

It would be nice to set those values with a parameter, something like this:
```html
  <div pf-form-group pf-label="foo" ratio="6:6">...</div>
```
And then it should look like this:
![screenshot from 2017-08-21 14-04-03](https://user-images.githubusercontent.com/22619452/29518454-aa34453e-8679-11e7-980b-fb2bf9c48ea1.png)
 
Thank you

**Comment by skateman** [comment]
@jeff-phillips-18 could you please take a look at this?

**Comment by dtaylor113** [comment]
> the label and input width in pf-form-group is fixed to 2:5.

Hi, what do you mean a ratio of 2:5?  Do you mean columns?

**Comment by skateman** [comment]
@dtaylor113 the `label` has a fixed `col-sm-2` class while the `input` has a `col-sm-5` and we can't change them :disappointed:

**Comment by dtaylor113** [comment]
Hi, I thought you could with pf-form-group attributes ```pf-label-class```, and there is a corresponding one for the actual for element: ```pf-input-class``` 

```
<p>Horizontal Form</p>
       <form class="form-horizontal">
         <pf-form-group pf-label="Name" required pf-label-class="col-sm-6" pf-input-class="col-sm-6">
           <input id="name" name="name" ng-model="item.name" type="text" required/>
         </pf-form-group>
         <pf-form-group pf-label="Description" pf-label-class="col-sm-6" pf-input-class="col-sm-6">
           <textarea id="description" name="description" ng-model="item.description">
             {{ item.description }}
           </textarea>
         </pf-form-group>
       </form>
```

**Comment by dtaylor113** [comment]
@Hyperkid123 , @skateman , does this resolve this issue?

**Comment by skateman** [comment]
@Hyperkid123 will be back on thursday and he'll verify this, thanks!

**Comment by Hyperkid123** [comment]
@dtaylor113 Yes  `pf-label-class="col-sm-6" pf-input-class="col-sm-6"`  works just fine. Thank you very much.

**Comment by skateman** [comment]
:tada: @Hyperkid123 please close this issue :trumpet:
