### ISSUE TITLE
App launcher update

### ISSUE THREAD

**Issue by LHinson** [patternfly/angular-patternfly#595]
The angular version of the app launcher menu is getting cut off here: http://www.patternfly.org/pattern-library/application-framework/launcher/#/code/angular

This relates to: https://github.com/patternfly/patternfly-org/issues/452

**Comment by amarie401** [comment]
@jeff-phillips-18 will this be changed in the pf-org repo or in the angular-pf repo? Seems that I'll have to change styling in the dropdowns.less file..

**Comment by jeff-phillips-18** [comment]
Looks to me like the issue is purely in the A-PF example code/styling.

**Comment by cdcabrera** [comment]
So the [app launcher was designed as a core PF piece](https://github.com/patternfly/patternfly/blob/master/src/less/application-launcher.less). Buttttttt the styling for the dropdown that app launcher wraps may need to be investigated further. 

A quick fix would be just to mess with the ```z-index``` on the app launcher less... a more thorough fix would be to investigate the drop down css
