### ISSUE TITLE
No CDN for angular-patternfly?

### ISSUE THREAD

**Issue by himdel** [patternfly/angular-patternfly#596]
Patternfly itself is on cdnjs (https://cdnjs.com/libraries/patternfly), all angular-patternfly dependencies seem to be there as well... but if you want to include angular-patternfly, you're out of luck :).

The only way is to include `https://www.patternfly.org/angular-patternfly/grunt-scripts/angular-patternfly.js` and `https://www.patternfly.org/angular-patternfly/css/angular-patternfly.css`, which ..may be suboptimal :). (And who knows which version is there.)

**Comment by jeff-phillips-18** [comment]
Yeah we should get angular-patternfly on cdnjs.

**Comment by MartinKolarik** [comment]
You can also use https://www.jsdelivr.com/package/npm/angular-patternfly
No need to setup anything.

**Comment by jeff-phillips-18** [comment]
I have a PR up on CDNJS to add Angular Patternfly: https://github.com/cdnjs/cdnjs/pull/12056

**Comment by dtaylor113** [comment]
Latest PR is https://github.com/cdnjs/cdnjs/pull/12056

**Comment by himdel** [comment]
Make that https://github.com/cdnjs/cdnjs/pull/12085 :)

**Comment by jeff-phillips-18** [comment]
https://github.com/cdnjs/cdnjs/pull/12085 has merged!

CDNJS support is now available!
