### ISSUE TITLE
Accessibility: Notification drawer expand & collapse links are inaccessible via keyboard navigation

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#599]
The `a ng-click`s in the header of the notification drawer need an empty `href=""` to be keyboard accessible (expand/collapse links).

Re [this comment](https://github.com/openshift/origin-web-console/pull/1326#issuecomment-325401834) on origin-web-console [PR 1326](https://github.com/openshift/origin-web-console/pull/1326)

Is there accessibility guidelines in upstream patternfly?  This would be a great topic @ that level.

@jeff-phillips-18

**Comment by cdcabrera** [comment]
Quite a few potentials for this fix:

- Per @amarie401 , ```href="javascript:void(0)"
- dump a ```tab-index="0" on there (last resort)
- ```ng-href="" ng-click="someEvent"```
- ```ng-href="" ng-click="someEvent($event)"```, and look at preventDefault in some form and maybe a hash in ng-href... though routing may be a concern

**Comment by jeff-phillips-18** [comment]
href="" will work just fine (in angular)

**Comment by cdcabrera** [comment]
href works... within some past projects, for future proofing, seen letting Angular generate all of the attributes

**Comment by jeff-phillips-18** [comment]
I assume you mean you'd prefer to go with ng-href ?  If so, I'm ok with that as well.

**Comment by jeff-phillips-18** [comment]
we don't want to simply tab-index="0" and we don't want to prevent default since we want to be able to activate these via the keyboard as well.

**Comment by cdcabrera** [comment]
agreed, the potential for funkiness is well, funky
