### ISSUE TITLE
Notification drawer blank state styling wrong

### ISSUE THREAD

**Issue by spadgett** [patternfly/angular-patternfly#604]
Looks like this was introduced in #587 

cc @jeff-phillips-18 @benjaminapetersen 

Before as `h1`:

<img width="976" alt="screen shot 2017-08-30 at 8 26 42 pm" src="https://user-images.githubusercontent.com/1167259/29900786-e255c8f8-8dc1-11e7-876b-cd02aeca976b.png">

After as `h4`:

<img width="970" alt="screen shot 2017-08-30 at 8 26 57 pm" src="https://user-images.githubusercontent.com/1167259/29900781-dc8b4c5e-8dc1-11e7-976a-bddefed984ba.png">

**Comment by spadgett** [comment]
The original `h1` seems more semantically correct to me. `h4` seems arbitrary since there's no `h1` / `h2` / `h3`.

**Comment by benjaminapetersen** [comment]
Hm. Yeah I wonder if semantically it could have just been a `p` tag as its not really even a heading for content.

**Comment by benjaminapetersen** [comment]
Running the demo locally looks like this:

![screen shot 2017-09-01 at 2 46 13 pm](https://user-images.githubusercontent.com/280512/29983560-83b0c71c-8f24-11e7-91d1-301a65ac8178.png)

The `h1` class just affects the heading space.  However, when we pull it into the console, it blows up the font size.

I do see `.showcase` classes appearing here and altering style as well, however, which might be related to what @jeff-phillips-18 mentioned on issue #607?

**Comment by jeff-phillips-18** [comment]
.showcase is a ng-docs page only thing. Just went in today. we will resolve it shortly.

**Comment by benjaminapetersen** [comment]
ok great!

**Comment by spadgett** [comment]
> Yeah I wonder if semantically it could have just been a p tag as its not really even a heading for content.

Agree

> The h1 class just affects the heading space. However, when we pull it into the console, it blows up the font size.

It looks like `class="h1"` in actually the problem in our console because of one of our styles

**Comment by cliffpyles** [comment]
According to the design spec, an empty state pattern requires a title. So from what I can tell, the larger font and spacing is actually the desired outcome (according to the spec). So do we need to deviate from the design spec, or should this be left as is? I'm attaching the design spec below for reference.

![image](https://user-images.githubusercontent.com/904039/30499024-ede28514-9a26-11e7-85d9-f28f41ea4836.png)

**Comment by jeff-phillips-18** [comment]
I think leaving it as an h4 should be OK, it is technically a header.

**Comment by cliffpyles** [comment]
Sounds good. I'll close the issue then.
