### ISSUE TITLE
Wizard mobile update

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/angular-patternfly#605]
Angular counterpart to https://github.com/patternfly/patternfly/pull/722

The purpose of this is to add a temporary simplified version of the wizard for mobile. This will be updated to offer a more robust option that will include all the lost functionality.

Related JIRA story: https://patternfly.atlassian.net/browse/OSUX-117

**Comment by jeff-phillips-18** [comment]
Fixed by #615
