### ISSUE TITLE
Drawer title appears to have fallen behind the accordion

### ISSUE THREAD

**Issue by benjaminapetersen** [patternfly/angular-patternfly#607]
I suspect with the latest changes to upstream [patternfly drawer](https://github.com/patternfly/patternfly/pull/717) updates.

![screen shot 2017-09-01 at 2 38 03 pm](https://user-images.githubusercontent.com/280512/29983307-32c5489c-8f23-11e7-9233-73515abbcf74.png)

I've pulled master & `npm install && bower install` 2x, don't think it is local.

@jeff-phillips-18 @matthewcarleton

**Comment by benjaminapetersen** [comment]
Quick diagnosis, both the `drawer-pf-title` and the `panel-group` are `position:absolute`.

**Comment by jeff-phillips-18** [comment]
This is a Showcase only issue due to changes made for the header area. This will not affect adopters.

**Comment by benjaminapetersen** [comment]
Unclear then why the demo looks wrong?  Is something that can be corrected?

**Comment by jeff-phillips-18** [comment]
Updating the header, made a changes that are effecting the examples. We will rectify shortly.
