### ISSUE TITLE
Minor Clean Up of Non-breaking Changes

### ISSUE THREAD

**Issue by cdcabrera** [patternfly/angular-patternfly#620]
Repository wide general clean up for maintenance which includes things such as trailing commas, re-declared variables, mismatched tags, etc. Couple of quick examples:

- https://github.com/patternfly/angular-patternfly/blob/master/src/charts/utilization-bar/utilization-bar-chart.component.js#L110
- https://github.com/patternfly/angular-patternfly/blob/master/test/navigation/application-launcher.spec.js#L44

These non-breaking changes seem to mostly appear within the examples and unit tests where we have limited linting applied

**Comment by amarie401** [comment]
Found another one. After thorough testing between ng-value and value on a radio button, it looks like this [line 112 in the application-launcher](https://github.com/patternfly/angular-patternfly/blob/master/src/navigation/application-launcher.component.js#L112) could also be improved by converting to a boolean.

**Comment by cdcabrera** [comment]
[Remove the extra $attrs around line 52](https://github.com/patternfly/angular-patternfly/pull/634/files#diff-48742c3be5e2ef4fde31834391ea710aR52).

**Comment by jeff-phillips-18** [comment]
@cdcabrera  Where are we with this? Is this still important?

**Comment by cdcabrera** [comment]
@jeff-phillips-18 the intention around this was kind of been lost, something for newer team members to use and get familiar with the code base. To keep it moving picked it back up today and started going through a bunch of pieces, be opening a PR this week around 10/11 or 12

**Comment by cdcabrera** [comment]
@jeff-phillips-18 @dtaylor113 

Came across some arrow function implementations while doing clean up... they appear to be limited to demos, but if our browser support is geared towards some older browser versions we should probably be careful. 

- src/table/tableview/examples/table-view-basic.js
- src/table/tableview/examples/table-view-with-toolbar.js

At some point we should probably consider a babel implementation so we can start using updated syntax.
