### ISSUE TITLE
Introduce Coveralls for continuous code coverage reporting

### ISSUE THREAD

**Issue by AllenBW** [patternfly/angular-patternfly#622]
https://coveralls.io/

Ok ok ok so what will this give us? Function by function (and more) reporting on if test coverage  movement per pr!  This is powerful because we can say "Oh hai, test coverage went down, add tests or yo pr isn't welcome here".  As unique contributors increase it could be a nice helper to ensure product quality over time (high test coverage). 

It is free for open source :trollface: 

### [Here is some sample coverage reporting](https://coveralls.io/builds/13153485)
<img width="1299" alt="screen shot 2017-09-13 at 11 00 46 am" src="https://user-images.githubusercontent.com/6640236/30384704-0bab4884-9873-11e7-8ccd-1a6f8a6f7fe7.png">

Thoughts @jeff-phillips-18 @dtaylor113 @cdcabrera ?

**Comment by dtaylor113** [comment]
Looks good!  I see there is a Karma plug-in (https://github.com/mattjmorrison/grunt-karma-coveralls).

**Comment by cdcabrera** [comment]
Agreed, If we can implement any addition that improves our ability to test, or explain testing, you've got my vote! (Some form of...) TDD for life =)

**Comment by dtaylor113** [comment]
Note that angular-patternfly uses code climate, which does have a code coverage plug-in: https://docs.codeclimate.com/v1.0/docs/configuring-test-coverage

Not sure how it compares to coveralls.
