### ISSUE TITLE
Update Karma Dependencies

### ISSUE THREAD

**Issue by amarie401** [patternfly/angular-patternfly#623]
How do we want to handle updating existing dependencies for karma and jasmine?

Is there any reason we can't do these updates?

@cdcabrera @cliffpyles @jeff-phillips-18 @dtaylor113

**Comment by dtaylor113** [comment]
Sorry, where is this 'ask' coming from?  Should be able to update existing dependencies as long as new versions support angular 1.5.   Need to update bower.json and package.json.   And possibly test/karma.conf.js if old properties have changed.

**Comment by amarie401** [comment]
I noticed that a lot of the dependencies were older. I wanted to know if it was safe to update existing dependencies as long as there weren't any major version changes.

**Comment by cdcabrera** [comment]
Updating the testing dependencies first would for sure help us avoid direct dist updates. Might also help call out anything more recent that may have updated within Angular 1.5ish +

And yeah, looks like some of the dependencies we have are a little dated when compared to Angular releases... the separation of Jasmine Core from the Karma Jasmine module should kind of be an indicator for us

**Comment by jeff-phillips-18** [comment]
I'm OK with updating dependencies that do not effect downstream, so any dev dependencies can be updated for sure.
