### ISSUE TITLE
Accordions do not have correct styling

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/angular-patternfly#627]
Incorrect colors and collapsed indicator always shows as if open

Angular PF Fixed Accordion: 
![image](https://user-images.githubusercontent.com/11633780/30640074-784a4164-9dcf-11e7-86e5-113905bed9bc.png)

PF Fixed Accordion:
![image](https://user-images.githubusercontent.com/11633780/30640133-bd821eaa-9dcf-11e7-9597-28aef38e88c5.png)

**Comment by cliffpyles** [comment]
This issue will need to be resolved when the accordion is implemented. To apply styles give `class="panel-default"` to the `uib-accordion-group`.

I've updated the documentation to indicate this also.

#634
