### ISSUE TITLE
create pfInfoStatusCard

### ISSUE THREAD

**Issue by AllenBW** [patternfly/angular-patternfly#629]
We have `pfAggregateStatusCard`, but what if you just want to display a few lines of text or whatever!!

Introducing, the `pfInfoStatusCard` 👍 

### Should look something like the two cards in the upper right of this img:
<img width="736" alt="screen shot 2017-09-20 at 3 20 07 pm" src="https://user-images.githubusercontent.com/6640236/30663034-3e784e02-9e17-11e7-9f66-23b6af330179.png">

### a closer look
<img width="414" alt="screen shot 2017-09-20 at 3 22 10 pm" src="https://user-images.githubusercontent.com/6640236/30663105-8e5f145a-9e17-11e7-98da-aeecdf48c59e.png"> 

As requested by @serenamarie125

**Comment by AllenBW** [comment]
@jeff-phillips-18 @dtaylor113 Can someone assign this to me and add enhancement as a label? (pretty please!!!)

**Comment by dtaylor113** [comment]
@AllenBW   Assigned to you and tagged.
