### ISSUE TITLE
Topology graph bindings/attributes revisit

### ISSUE THREAD

**Issue by skateman** [patternfly/angular-patternfly#631]
Hi,

as we agreed with @serenamarie125 we're planning to enhance the topology graph with some features introduced in [my UI components PR](https://github.com/ManageIQ/ui-components/issues/75). We looked into the [attributes/bindings](http://www.patternfly.org/angular-patternfly/#/api/patternfly.charts.component:pfTopology) and found out that it's kinda complicated.

We'd like to remove:
* `icons` - and use a `fonticon` (CSS class) or `fileicon` (URL) directly on a node.
* `nodes` - attribute as it is totally unnecessary, positioning can be done [programmatically](https://github.com/ManageIQ/ui-components/pull/75/files#diff-2159ccbcf34b3c990b581bda165dccf9R163)
* `search`- it should live in a parent controller/component
* `kinds` - totally unnecessary, a parent controller/component can send the reduced set of data

Also the `items` could be renamed to `nodes` as it would make more sense :wink:

As the organization of these bindings/attributes might be intentional, I'd like to propose to create a totally new primitive component, let's name it e.g. `topologyCanvas` which will do one job: render the topology itself. This could contain our refactored code and the `pfTopology` could contain this component in the future and do the translations between the bindings/attributes if the format is really necessary.

@serenamarie125 and @jeff-phillips-18 what do you guys think? @hyperkid123 can start working on this immediately.

**Comment by serenamarie125** [comment]
@skateman wonder if we can have a quick meeting to discuss the extent of the changes.  We are proposing some new changes for the topology pattern and would just like to make sure that there won't be conflicts.  I'll set something up!

**Comment by skateman** [comment]
@serenamarie125 not sure if @hyperkid123 can join tomorrow, he's an intern and AFAIK he works on Tuesdays and Thursdays only.

**Comment by Hyperkid123** [comment]
It depends when. I should be available after 8pm(CEST) tomorrow and whole weekend.

**Comment by serenamarie125** [comment]
@skateman yes we agree
Based on the 9/22 meeting with @jeff-phillips-18 @dgutride @Nlcwong @skateman @Hyperkid123 

Please leave the existing pfTopology component untouched and create a new pfTopologyMap component in a new Topology area.  We will later create a pfTopologyView to support filtering, details, etc.

**Comment by beanh66** [comment]
Looks like this issue is being worked on in the following PR: https://github.com/patternfly/angular-patternfly/pull/633
