### ISSUE TITLE
Canvas is a directive, consider rewriting it as a component

### ISSUE THREAD

**Issue by bleathem** [patternfly/angular-patternfly#636]
Consider rewriting the canvas directive as a component.

From slack:
>dana [6:27 AM] 
>Canvas is actually a directive internally - it has a link function and binds to several document listeners

**Comment by beanh66** [comment]
@jeff-phillips-18 I chatted with @dgutride briefly on this issue. Curious if you have any thoughts on the sentiment above?

**Comment by jeff-phillips-18** [comment]
Should be an easy fix.

**Comment by jeff-phillips-18** [comment]
there are a couple of other directives that ought be components as well

https://github.com/patternfly/angular-patternfly/blob/master/src/canvas-view/canvas-editor/toolbox-items.directive.js

https://github.com/patternfly/angular-patternfly/blob/master/src/canvas-view/canvas/node-toolbar.directive.js

**Comment by dtaylor113** [comment]
Hi, the pfCanvas and pfCanvasEditor are rather complex directives which use a MVVM pattern.  The code was originally ported from a "SVG and AngularJS Flowchart" article.  [Read this](https://www.codeproject.com/Articles/709340/Implementing-a-Flowchart-with-SVG-and-AngularJS) for some background information and architectural decisions.

**Comment by amarie401** [comment]
Thanks for the background info @dtaylor113. The pfCanvas is definitely more complex than I originally thought when I started the conversion process. Myself and @cliffpyles @TheRealJon were going to try to tackle it, is this something that we really want to convert to a component or should we hold off?

**Comment by dtaylor113** [comment]
Hi, just spoke to @dgutride about the history behind this "ask".  I think this issue was filed just because, in general, we should stay away from using directives as they are not supported in Angular 2+ (nor $scope, $broadcast, $emit, etc...).   I don't believe any team has specifically asked for the pfCanvas to be converted.  IMO converting this probably doesn't buy us much.  I certainly wouldn't pick up this work as a way to 'dive into angular-patternfly'.  -thanks :-)

**Comment by amarie401** [comment]
I agree @dtaylor113

**Comment by dtaylor113** [comment]
@jeff-phillips-18 and I agree that converting it to a component would be 'real nice' :-) and would allow us to eventually port it to angular-patternfly-ng.   I think a good start would be to see if you could convert it to a component and use the new `bindings` and replace/move the `post-link` directive methods to perhaps $postLink.   I know the canvas directives use a lot of `$scope` and `$broadcast/$emit` to communicate between themselves.  I would suggest leaving `$scope` in for now and just concentrate on doing the bare minimum to convert them to components  -if you decide you want to take this work on.   :-)  Thanks!
