### ISSUE TITLE
Linter for code within unit tests and ng-docs

### ISSUE THREAD

**Issue by cdcabrera** [patternfly/angular-patternfly#646]
Implement some form linter for unit tests. Research and possibly do the same for ng-docs to avoid future clean up tasks like #620 

Related PR #644

**Comment by cdcabrera** [comment]
@jeff-phillips-18 & @dtaylor113 input appreciated

This may be a bit larger than simply turning eslint on for the test directory... first run throws back 718 "kinda, but not really problems" such as...

```shell
 ...
  315:5   error  All "var" declarations must be at the top of the function scope  vars-on-top

✖ 718 problems (718 errors, 0 warnings)
```

With the majority of the issues being ```"var" declarations must be at the top````. Can do a couple of things:
- continue going in and correcting this manually
  - then maybe taking a look at some automated form of "beautify" or "prettify" 
- or/and look at relaxing the eslint config, mostly in the errors to warnings area

**Comment by jeff-phillips-18** [comment]
I would be ok with relaxing the `All "var" declarations must be at the top of the function scope` rule

**Comment by dtaylor113** [comment]
Me too
