### ISSUE TITLE
JS actions to compileAsHtml templates

### ISSUE THREAD

**Issue by AllenBW** [patternfly/angular-patternfly#649]
so the ask is this, you want to add an ng-click, or a popover or ANYthing to an info status card row item
the problem is this, not doable because of the way trustashtml was not meant to build directives

so the solution is this, (well inspired by this) a directive that watches the template and recompiles it when necessary https://docs.angularjs.org/api/ng/service/$compile#example

**Comment by AllenBW** [comment]
@jeff-phillips-18 can ya fill me up with labels and assign to meeeee ? ❤️ 🙇‍♀️

**Comment by dtaylor113** [comment]
Hmm...only issue is that we are trying to stay away from `$compile` because it is not supported in angular 2+

**Comment by AllenBW** [comment]
SNAP, good headsup @dtaylor113  didn't know, i saw it used in [heatmap](https://github.com/patternfly/angular-patternfly/blob/master/src/charts/heatmap/heatmap.component.js#L165) and thought it was ok....

**Comment by AllenBW** [comment]
@dtaylor113 ya think that makes this ask doa?

**Comment by dtaylor113** [comment]
yeah, heatmap is the only remaining component with $compile, just because we haven't had time to investigate how to get it working without a $compile.

**Comment by AllenBW** [comment]
Ok gonna close this, will hand role the thing in the app.   Thanks for the eyes @dtaylor113 🙇‍♀️
