### ISSUE TITLE
The donut pct chart should allow for configurable colors

### ISSUE THREAD

**Issue by waldenraines** [patternfly/angular-patternfly#66]
Instead of setting the colors of the donut percentage chart in the directive itself we should add classes that describe the desired state and set the colors in patternfly.css.  This will allow consumers of angular-patternfly to override these colors as needed.

See also https://github.com/patternfly/angular-patternfly/pull/64/files#r38665528

**Comment by dtaylor113** [comment]
Currently, the donut chart is using patternfly colors:
- 'no thresholds' = patternfly.pfPaletteColors.blue
- 'ok' = patternfly.pfPaletteColors.green
- 'waring' = patternfly.pfPaletteColors.orange
- 'error' = patternfly.pfPaletteColors.red
I do not believe we want users to be able to override these.  Please reopen if disagree.
Thanks,
- Dave
