### ISSUE TITLE
pfDonutPctChart tooltip label shows % as well as units

### ISSUE THREAD

**Issue by cshinn** [patternfly/angular-patternfly#671]
The demo charts on [pfDonutPctChart](http://www.patternfly.org/angular-patternfly/#/api/patternfly.charts.component:pfDonutPctChart) display both a percent symbol and units when hovered as shown here. 
<img width="276" alt="screen shot 2017-11-06 at 3 03 58 pm" src="https://user-images.githubusercontent.com/3300756/32461510-1355c184-c304-11e7-9866-ff0e6d541d7a.png">

They should either show only %, or the tooltip should be changed to show absolute numbers with units rather than a percentage.

**Comment by TheRealJon** [comment]
Adding a `tooltip` attribute that will allow for selection between "percent", "scalar", or "both".
