### ISSUE TITLE
Provide implementation for the Modal Overlay

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/angular-patternfly#673]
Provide implementation for the modal overlay as documented here: http://www.patternfly.org/pattern-library/forms-and-controls/modal-overlay/

Note that @jeff-phillips-18 implemented this in OpenShift, but this has not yet been contributed back to PatternFly.  Also, I think he has some suggestions re: implementation that should be considered.

**Comment by serenamarie125** [comment]
Note: associated Issue in PatternFly React: https://github.com/patternfly/patternfly-react/issues/68

**Comment by dtaylor113** [comment]
Please see the Pattern [design](http://www.patternfly.org/pattern-library/forms-and-controls/modal-overlay/#design) when implementing this.

This is implemented in angular-patternfly's `pfWizard`'s outer container, meaning the title bar with 'x' close icon, the body, and the footer which contains the action buttons.

First step would be to create a skeleton new component which simply has the HTML and LESS/CSS to render the modal overview.

Next, in the new `pfModalOverlay` component, the title bar should be configured via some passed in JSON config obj  which sets the titleText, and has a boolean to show/hide the 'x' icon (should default to 'true' if not specified).   The body should be transcluded.  The footer should be configured via some JSON config obj, an array of actionButtons objects with callback functions.
