### ISSUE TITLE
pfToolbar actions layout is incorrect at mobile sizes

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/angular-patternfly#681]
![image](https://user-images.githubusercontent.com/11633780/33281970-1003368e-d375-11e7-8c1e-82fd65b23a34.png)

![image](https://user-images.githubusercontent.com/11633780/33281987-25261d1a-d375-11e7-8b5f-40c2bdea3931.png)

**Comment by dtaylor113** [comment]
PF Test Page for toolbar does mobile this way:

![image](https://user-images.githubusercontent.com/12733153/34583401-a10ee5ac-f165-11e7-912a-dd22703d386e.png)

**Comment by jcaianirh** [comment]
Looking into this issue. 

The original thought was that this is an angular-patternfly issue, however, looking at the screenshots of behavior below, seems as though the fix should be targeted to patternfly core css.
Angular PatternFly Behavior:

![angularpatternflytoolbarbuttonwrap](https://user-images.githubusercontent.com/35978579/35704106-4f52179e-076c-11e8-8204-3019b825bd6b.png)

PatternFly Core Behavior:

![patternflycoretoolbarbuttonwrap](https://user-images.githubusercontent.com/35978579/35704131-7318aa9e-076c-11e8-806e-911ef3a7ce55.png)

**Comment by andresgalante** [comment]
Hi @jeff-phillips-18 , I just had a talk with @jcaianirh 

This is a CSS known issue on PF3. We could fix it on pf3 by restructuring the toolbar with flex instead of floats, but that will generate regresions on users using the toolbar component.

What do you think? Can we leave this one as is and deliver a better solution on pfnext?

**Comment by dtaylor113** [comment]
Hi @andresgalante, is there a less/css solution we could implement in angular-patternfly; override pf core toolbar less?

**Comment by jeff-phillips-18** [comment]
@andresgalante I wouldn't want to restructure the toolbar at this point for this issue. I would leave it be and fix in the next major release.

**Comment by andresgalante** [comment]
@dtaylor113 yes, you can re write the CSS, the problem stands the same, you'll generate a problem to everyone consuming it.
