### ISSUE TITLE
Add LESS-to-SASS Converter

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/angular-patternfly#688]
https://www.npmjs.com/package/grunt-lassie

**Comment by dtaylor113** [comment]
Hi @jeff-phillips-18, @amarie401, @TheRealJon ,

I've added 'lessToSass' and 'sass' task to angular-patternfly.  The resulting sass-2-css is almost identical to the original (less-2-css):  https://www.diffnow.com/?report=jh54y

@TheRealJon, wondering if all these [rules](https://github.com/dtaylor113/angular-patternfly/blob/add-less-to-sass/Gruntfile.js#L142) are necessary?

Results in a `dist/sass` directory.  Still have to add  the `grunt build --sass` feature to angular-patternfly.

**Comment by TheRealJon** [comment]
@dtaylor113 All of them should not be necessary. There are a few that are specific to Ruby related tooling and also specific to the patternfly core repo. Once you submit a PR, I can comment on which rules are unnecessary, or I can submit a PR to your fork if you want.

**Comment by TheRealJon** [comment]
As you may have noticed, I am the publisher of that grunt-lassie package. I forked an existing and abandoned converted (grunt-less-to-sass) and published it so that we can update it if we need to. Some of these conversion rules could be added to that tool so that we don't need to copy/paste rules between projects.

**Comment by dtaylor113** [comment]
Thanks @TheRealJon, Either way works for me.  Feel free to post PR to my branch, or when I'm ready we can handle unneeded rules via PR comments.  -thanks

**Comment by TheRealJon** [comment]
@dtaylor113 This PR should remove all the unneeded rules:
https://github.com/dtaylor113/angular-patternfly/pull/5

**Comment by dtaylor113** [comment]
Thanks @TheRealJon !
