### ISSUE TITLE
angular-ui-bootstrap Datepicker component does not include PatternFly styling

### ISSUE THREAD

**Issue by mcarrano** [patternfly/angular-patternfly#711]
Apparently pfDateTimepicker was dropped from the current PatternFly release in favor of a recommendation to use the angular-ui-boostrap Datepicker component (see http://angular-ui.github.io/bootstrap/versioned-docs/1.0.0/). While this meets the functional requirements for selecting dates, the styling of this component is inconsistent with the PatternFly design here: http://www.patternfly.org/pattern-library/forms-and-controls/datepicker/#design

The angular-ui-bootstrap component should be restyled to be more consistent with the PatternFly design.

**Comment by dtaylor113** [comment]
### Here are both components side-by-side:

**Patternfly Design** 
![image](https://user-images.githubusercontent.com/12733153/35978110-d11e407c-0cb2-11e8-8111-f088b99353ca.png) 

**ui.bootstrap.datepicker**
![image](https://user-images.githubusercontent.com/12733153/35978167-fbc94b64-0cb2-11e8-8ea5-42b3c7479329.png)

**Comment by dtaylor113** [comment]
Since this is a styling enhancement, I don't think we need a new component, rather we would override the ui.bootstrap.datepicker css selectors and maybe able to just create an ngDoc example which uses the native ui.bootstrap.datepicker and the angular-patternfly datepicker css overrides.

**Comment by mcarrano** [comment]
Yes, I agree @dtaylor113 . I don't really care that the behaviors and layout are not exactly the same. If we can just override the CSS do it appears more consistent with the core Datepicker, that will be sufficient. The only thing I wonder is whether it's possible to hide the column of numbers (weeks of the year?) down the left hand side. IMO they just add clutter and are not particularly useful in most cases.
