### ISSUE TITLE
pfTableView: default sorting doesn't change based on visibility of checkboxes column

### ISSUE THREAD

**Issue by akieling** [patternfly/angular-patternfly#715]
**Current behavior**
When the table shows checkboxes, the default sorting is by the second column.
When the table doesn't show checkboxes, the default sorting is by the **second** column.

**Expected behavior**
When the table shows checkboxes, the default sorting is by the second column.
When the table doesn't show checkboxes, the default sorting is by the **first** column.

**Comment by dtaylor113** [comment]
Has to do with how we set default [dt](https://github.com/patternfly/angular-patternfly/blob/master/src/table/tableview/table-view.component.js#L28) options.  Need to check if `showCheckboxes` is true or not.  If true, then column 1 is used (0 = checkbox column).  If false, dt order default should be 0.
