### ISSUE TITLE
If jQuery is not being used in application , than pfDonutPctChart directive having issue with $.extend function 

### ISSUE THREAD

**Issue by kamleshverma1** [patternfly/angular-patternfly#72]
If jQuery is not being used in application , than in pfDonutPctChart directive having issue with $.extend function , this is jQuery function , and here jquery is not being used , so either  $.extend wherever is used that should be not there. or we should have our own custom javascript extend function , that will merge two object and return in to the first object .

**Comment by dtaylor113** [comment]
Hi,
We use $.extend in several of the angular-patternfly charts, as well as a few components in patternfly itself:

Targets
    Occurrences of '$.extend' in Project
Found Occurrences  (143 usages found)
    Unclassified occurrence  (141 usages found)
        angular-patternfly  (141 usages found)
            lib/patternfly/components/bootstrap-combobox/js  (2 usages found)
                bootstrap-combobox.js  (2 usages found)
                    (27: 20) this.options = $.extend({}, $.fn.combobox.defaults, options);
                    (129: 17) var pos = $.extend({}, this.$element.position(), {
            lib/patternfly/components/bootstrap-datepicker/dist/js  (7 usages found)
                bootstrap-datepicker.js  (7 usages found)
                    (67: 4) $.extend(a, extras);
                    (138: 14) this._o = $.extend({}, this._o, opts);
                    (140: 21) var o = this.o = $.extend({}, this._o);
                    (1466: 14) xopts = $.extend({}, defaults, elopts, options),
                    (1469: 13) opts = $.extend({}, defaults, locopts, elopts, options);
                    (1474: 65) $this.data('datepicker', (data = new DateRangePicker(this, $.extend(opts, ropts))));
                    (1699: 15) var seps = $.extend([], format.separators);
            lib/patternfly/components/bootstrap-datepicker/js  (7 usages found)
                bootstrap-datepicker.js  (7 usages found)
                    (83: 4) $.extend(a, extras);
                    (154: 14) this._o = $.extend({}, this._o, opts);
                    (156: 21) var o = this.o = $.extend({}, this._o);
                    (1482: 14) xopts = $.extend({}, defaults, elopts, options),
                    (1485: 13) opts = $.extend({}, defaults, locopts, elopts, options);
                    (1490: 65) $this.data('datepicker', (data = new DateRangePicker(this, $.extend(opts, ropts))));
                    (1715: 15) var seps = $.extend([], format.separators);
            lib/patternfly/components/bootstrap-select/dist/js  (1 usage found)
                bootstrap-select.js  (1 usage found)
                    (1593: 24) var config = $.extend({}, Selectpicker.DEFAULTS, $.fn.selectpicker.defaults || {}, $this.data(), options);
            lib/patternfly/components/bootstrap-select/js  (1 usage found)
                bootstrap-select.js  (1 usage found)
                    (1570: 24) var config = $.extend({}, Selectpicker.DEFAULTS, $.fn.selectpicker.defaults || {}, $this.data(), options);
            lib/patternfly/components/bootstrap-treeview/public/js  (18 usages found)
                bootstrap-treeview.js  (18 usages found)
                    (158: 16) this.tree = $.extend(true, [], options.data);
                    (161: 18) this.options = $.extend({}, _default.settings, options);
                    (375: 43) this.$element.trigger('nodeExpanded', $.extend(true, {}, node));
                    (383: 44) this.$element.trigger('nodeCollapsed', $.extend(true, {}, node));
                    (416: 43) this.$element.trigger('nodeSelected', $.extend(true, {}, node));
                    (424: 45) this.$element.trigger('nodeUnselected', $.extend(true, {}, node));
                    (444: 42) this.$element.trigger('nodeChecked', $.extend(true, {}, node));
                    (452: 44) this.$element.trigger('nodeUnchecked', $.extend(true, {}, node));
                    (472: 43) this.$element.trigger('nodeDisabled', $.extend(true, {}, node));
                    (480: 42) this.$element.trigger('nodeEnabled', $.extend(true, {}, node));
                    (870: 13) options = $.extend({}, _default.options, options);
                    (902: 13) options = $.extend({}, _default.options, options);
                    (1080: 13) options = $.extend({}, _default.options, options);
                    (1107: 13) options = $.extend({}, _default.searchOptions, options);
                    (1142: 43) this.$element.trigger('searchComplete', $.extend(true, {}, results));
                    (1152: 13) options = $.extend({}, { render: true }, options);
                    (1162: 42) this.$element.trigger('searchCleared', $.extend(true, {}, results));
                    (1242: 45) $.data(this, pluginName, new Tree(this, $.extend(true, {}, options)));
            lib/patternfly/components/bootstrap-treeview/src/js  (18 usages found)
                bootstrap-treeview.js  (18 usages found)
                    (158: 16) this.tree = $.extend(true, [], options.data);
                    (161: 18) this.options = $.extend({}, _default.settings, options);
                    (375: 43) this.$element.trigger('nodeExpanded', $.extend(true, {}, node));
                    (383: 44) this.$element.trigger('nodeCollapsed', $.extend(true, {}, node));
                    (416: 43) this.$element.trigger('nodeSelected', $.extend(true, {}, node));
                    (424: 45) this.$element.trigger('nodeUnselected', $.extend(true, {}, node));
                    (444: 42) this.$element.trigger('nodeChecked', $.extend(true, {}, node));
                    (452: 44) this.$element.trigger('nodeUnchecked', $.extend(true, {}, node));
                    (472: 43) this.$element.trigger('nodeDisabled', $.extend(true, {}, node));
                    (480: 42) this.$element.trigger('nodeEnabled', $.extend(true, {}, node));
                    (870: 13) options = $.extend({}, _default.options, options);
                    (902: 13) options = $.extend({}, _default.options, options);
                    (1080: 13) options = $.extend({}, _default.options, options);
                    (1107: 13) options = $.extend({}, _default.searchOptions, options);
                    (1142: 43) this.$element.trigger('searchComplete', $.extend(true, {}, results));
                    (1152: 13) options = $.extend({}, { render: true }, options);
                    (1162: 42) this.$element.trigger('searchCleared', $.extend(true, {}, results));
                    (1242: 45) $.data(this, pluginName, new Tree(this, $.extend(true, {}, options)));
            lib/patternfly/components/bootstrap/dist/js  (16 usages found)
                bootstrap.js  (16 usages found)
                    (191: 22) this.options   = $.extend({}, Button.DEFAULTS, options)
                    (474: 21) var options = $.extend({}, Carousel.DEFAULTS, $this.data(), typeof option == 'object' && option)
                    (507: 19) var options = $.extend({}, $target.data(), $this.data())
                    (550: 26) this.options       = $.extend({}, Collapse.DEFAULTS, options)
                    (705: 21) var options = $.extend({}, Collapse.DEFAULTS, $this.data(), typeof option == 'object' && option)
                    (1204: 21) var options = $.extend({}, Modal.DEFAULTS, $this.data(), typeof option == 'object' && option)
                    (1234: 57) var option  = $target.data('bs.modal') ? 'toggle' : $.extend({ remote: !/#/.test(href) && href }, $target.data(), $this.data())
                    (1326: 24) (this._options = $.extend({}, this.options, { trigger: 'manual', selector: '' })) :
                    (1335: 15) options = $.extend({}, this.getDefaults(), this.$element.data(), options)
                    (1515: 33) $.offset.setOffset($tip[0], $.extend({
                    (1611: 16) elRect = $.extend({}, elRect, { width: elRect.right - elRect.left, height: elRect.bottom - elRect.top })
                    (1617: 12) return $.extend({}, elRect, scroll, outerDims, elOffset)
                    (1787: 22) Popover.DEFAULTS = $.extend({}, $.fn.tooltip.Constructor.DEFAULTS, {
                    (1798: 23) Popover.prototype = $.extend({}, $.fn.tooltip.Constructor.prototype)
                    (1891: 27) this.options        = $.extend({}, ScrollSpy.DEFAULTS, options)
                    (2218: 20) this.options = $.extend({}, Affix.DEFAULTS, options)
            lib/patternfly/components/bootstrap/js  (16 usages found)
                affix.js  (1 usage found)
                    (17: 20) this.options = $.extend({}, Affix.DEFAULTS, options)
                button.js  (1 usage found)
                    (18: 22) this.options   = $.extend({}, Button.DEFAULTS, options)
                carousel.js  (2 usages found)
                    (180: 21) var options = $.extend({}, Carousel.DEFAULTS, $this.data(), typeof option == 'object' && option)
                    (213: 19) var options = $.extend({}, $target.data(), $this.data())
                collapse.js  (2 usages found)
                    (18: 26) this.options       = $.extend({}, Collapse.DEFAULTS, options)
                    (173: 21) var options = $.extend({}, Collapse.DEFAULTS, $this.data(), typeof option == 'object' && option)
                modal.js  (2 usages found)
                    (294: 21) var options = $.extend({}, Modal.DEFAULTS, $this.data(), typeof option == 'object' && option)
                    (324: 57) var option  = $target.data('bs.modal') ? 'toggle' : $.extend({ remote: !/#/.test(href) && href }, $target.data(), $this.data())
                popover.js  (2 usages found)
                    (24: 22) Popover.DEFAULTS = $.extend({}, $.fn.tooltip.Constructor.DEFAULTS, {
                    (35: 23) Popover.prototype = $.extend({}, $.fn.tooltip.Constructor.prototype)
                scrollspy.js  (1 usage found)
                    (19: 27) this.options        = $.extend({}, ScrollSpy.DEFAULTS, options)
                tooltip.js  (5 usages found)
                    (78: 24) (this._options = $.extend({}, this.options, { trigger: 'manual', selector: '' })) :
                    (87: 15) options = $.extend({}, this.getDefaults(), this.$element.data(), options)
                    (267: 33) $.offset.setOffset($tip[0], $.extend({
                    (363: 16) elRect = $.extend({}, elRect, { width: elRect.right - elRect.left, height: elRect.bottom - elRect.top })
                    (369: 12) return $.extend({}, elRect, scroll, outerDims, elOffset)
            lib/patternfly/components/datatables-colreorder/js  (3 usages found)
                dataTables.colReorder.js  (3 usages found)
                    (419: 11) "init": $.extend( true, {}, ColReorder.defaults, opts ),
                    (774: 22) var aSearchCopy = $.extend( true, [], oState.aoSearchCols );
                    (796: 27) var stateColumnsCopy = $.extend( true, [], oState.columns );
            lib/patternfly/components/datatables-colvis/js  (1 usage found)
                dataTables.colVis.js  (1 usage found)
                    (320: 3) $.extend( true, this.s, ColVis.defaults, init );
            lib/patternfly/components/datatables/media/js  (37 usages found)
                jquery.dataTables.js  (37 usages found)
                    (386: 6) $.extend( true, user[hungarianKey], user[key] );
                    (603: 14) var oCol = $.extend( {}, DataTable.models.oColumn, oDefaults, {
                    (616: 24) searchCols[ iCol ] = $.extend( {}, DataTable.models.oSearch, searchCols[ iCol ] );
                    (676: 4) $.extend( oCol, oOptions );
                    (1010: 15) var oData = $.extend( true, {}, DataTable.models.oRow, {
                    (2453: 5) $.extend( true, data, newData );
                    (2511: 30) oSettings.jqXHR = $.ajax( $.extend( baseAjax, {
                    (2523: 30) oSettings.jqXHR = $.ajax( $.extend( baseAjax, ajax ) );
                    (4926: 13) order:   $.extend( true, [], settings.aaSorting ),
                    (4983: 27) settings.oLoadedState = $.extend( true, {}, state );
                    (5008: 4) $.extend( settings.oPreviousSearch, _fnSearchToHung( state.search ) );
                    (5022: 5) $.extend( settings.aoPreSearchCols[i], _fnSearchToHung( col.search ) );
                    (5150: 6) $.extend( true, out[prop], val );
                    (6124: 35) _fnCamelToHungarian( defaults, $.extend( oInit, $this.data() ) );
                    (6176: 20) var oSettings = $.extend( true, {}, DataTable.models.oSettings, {
                    (6208: 23) oInit = _fnExtend( $.extend( true, {}, defaults ), oInit );
                    (6280: 5) $.extend( oClasses, DataTable.ext.oJUIClasses, oInit.oClasses );
                    (6297: 5) $.extend( oClasses, DataTable.ext.classes, oInit.oClasses );
                    (6327: 4) $.extend( true, oLanguage, oInit.oLanguage );
                    (6341: 7) $.extend( true, oLanguage, json );
                    (7588: 10) return $.extend( {
                    (8524: 3) $.extend( cells.selector, {
                    (8719: 33) _fnFilterComplete( settings, $.extend( {}, settings.oPreviousSearch, {
                    (8746: 5) $.extend( preSearch[ column ], {
                    (11479: 14) "oSearch": $.extend( {}, DataTable.models.oSearch ),
                    (13941: 10) 			 *    $.extend( $.fn.dataTable.ext.type.order, {
                    (13950: 10) 			 *    $.extend( $.fn.dataTable.ext.order, {
                    (14014: 2) $.extend( _ext, {
                    (14027: 2) $.extend( DataTable.ext.classes, {
                    (14104: 2) $.extend( DataTable.ext.oJUIClasses, DataTable.ext.classes, {
                    (14179: 2) $.extend( extPagination, {
                    (14204: 2) $.extend( true, DataTable.ext.renderer, {
                    (14315: 2) $.extend( DataTable.ext.type.detect, [
                    (14376: 2) $.extend( DataTable.ext.type.search, {
                    (14464: 2) $.extend( _ext.type.order, {
                    (14508: 2) $.extend( true, DataTable.ext.renderer, {
                    (14668: 2) $.extend( DataTable.ext.internal, {
            lib/patternfly/components/matchHeight  (1 usage found)
                jquery.matchHeight.js  (1 usage found)
                    (77: 20) return $.extend(opts, options);
            lib/patternfly/dist/js  (6 usages found)
                patternfly.js  (3 usages found)
                    (77: 5) $.extend(true, $.fn.dataTable.defaults, {
                    (103: 5) $.extend($.fn.dataTableExt.oStdClasses, {
                    (121: 5) $.extend($.fn.dataTableExt.oPagination, {
                patternfly.min.js  (3 usages found)
                    (1: 1204) $.extend
                    (1: 1920) $.extend
                    (1: 2443) $.extend
            src/charts/donut  (1 usage found)
                donut-pct-chart-directive.js  (1 usage found)
                    (334: 25) $scope.config = $.extend(true, c3ChartDefaults.getDefaultDonutConfig(), $scope.config);
            src/charts/sparkline  (2 usages found)
                sparkline-chart.directive.js  (2 usages found)
                    (289: 25) $scope.config = $.extend(true, angular.copy($scope.defaultConfig), $scope.config);
                    (298: 24) scope.config = $.extend(true, angular.copy(scope.defaultConfig), scope.config);
            src/views/datalist  (2 usages found)
                data-list-directive.js  (2 usages found)
                    (225: 27) $scope.config = $.extend(true, angular.copy($scope.defaultConfig), $scope.config);
                    (236: 26) scope.config = $.extend(true, angular.copy(scope.defaultConfig), scope.config);
            src/views/datatiles  (2 usages found)
                data-tiles-directive.js  (2 usages found)
                    (222: 25) $scope.config = $.extend(true, angular.copy($scope.defaultConfig), $scope.config);
                    (231: 26) scope.config = $.extend(true, angular.copy(scope.defaultConfig), scope.config);
    Usage in comments  (2 usages found)
        angular-patternfly  (2 usages found)
            lib/patternfly/components/jquery/dist  (1 usage found)
                jquery.js  (1 usage found)
                    (6524: 17) // Not quite $.extend, this won't overwrite existing keys.
            lib/patternfly/components/jquery/src  (1 usage found)
                effects.js  (1 usage found)
                    (273: 17) // Not quite $.extend, this won't overwrite existing keys.

**Comment by dtaylor113** [comment]
Hi,
We use $.extend in several angular-patternfly charts, as well as patternfly itself:

Targets
    Occurrences of '$.extend' in Project
Found Occurrences  (143 usages found)
    Unclassified occurrence  (141 usages found)
        angular-patternfly  (141 usages found)
            lib/patternfly/components/bootstrap-combobox/js  (2 usages found)
            lib/patternfly/components/bootstrap-datepicker/dist/js  (7 usages found)
            lib/patternfly/components/bootstrap-datepicker/js  (7 usages found)
            lib/patternfly/components/bootstrap-select/dist/js  (1 usage found)
            lib/patternfly/components/bootstrap-select/js  (1 usage found)
            lib/patternfly/components/bootstrap-treeview/public/js  (18 usages found)
            lib/patternfly/components/bootstrap-treeview/src/js  (18 usages found)
            lib/patternfly/components/bootstrap/dist/js  (16 usages found)
            lib/patternfly/components/bootstrap/js  (16 usages found)
            lib/patternfly/components/datatables-colreorder/js  (3 usages found)
            lib/patternfly/components/datatables-colvis/js  (1 usage found)
            lib/patternfly/components/datatables/media/js  (37 usages found)
            lib/patternfly/components/matchHeight  (1 usage found)
            lib/patternfly/dist/js  (6 usages found)
            src/charts/donut  (1 usage found)
            src/charts/sparkline  (2 usages found)
            src/views/datalist  (2 usages found)
            src/views/datatiles  (2 usages found)

We will look into alternatives to $.extend in angular-patternfly.
Thank you,
- Dave

**Comment by erundle** [comment]
$scope.config = angular.extend({}, c3ChartDefaults.getDefaultDonutConfig(), $scope.config);

**Comment by kmkanagaraj** [comment]
@erundle  :+1:

**Comment by dtaylor113** [comment]
Hi,
I'm trying:

$scope.config = angular.*merge*({}, c3ChartDefaults.getDefaultDonutConfig(),
$scope.config);

..as angular.extend doesn't support 'deep-copy'.


On Tue, Sep 8, 2015 at 11:37 AM, Kanagaraj M <notifications@github.com>
wrote:

> @erundle <https://github.com/erundle> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/patternfly/angular-patternfly/issues/72#issuecomment-138602895>
> .
>



-- 
Dave Taylor
Principle Software Engineer
(978) 392 - 1016
