### ISSUE TITLE
pfToolbar: only show second toolbar row when there are active filters

### ISSUE THREAD

**Issue by alexkieling** [patternfly/angular-patternfly#720]
Based on PatternFly's Toolbar page and the pattern implementation in Patternfly NG, the second toolbar row should only be visible when there are active filters.
References:
http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/
https://rawgit.com/patternfly/patternfly-ng/master-dist/dist-demo/#/toolbar

**Comment by dtaylor113** [comment]
Not sure that is accurate, see http://www.patternfly.org/pattern-library/forms-and-controls/toolbar/#design
9. Content and Results Count: ..."If no filters are applied, only the total number of items and the item type are displayed (e.g. 40 Virtual Machines). "

**Comment by dtaylor113** [comment]
Patternfly-React seems to also show the second row when no filters.  [example](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?selectedKind=Toolbar&selectedStory=Toolbar&full=0&down=1&left=1&panelRight=0&downPanel=storybooks%2Fstorybook-addon-knobs)
Both Angular-Patternfly and Patternfly-React do not display the results count right-aligned though.

**Comment by akieling** [comment]
@dtaylor113 It looks like the lack of consistency across the documentation is causing confusion and leading to different implementations.

**Comment by dtaylor113** [comment]
@akieling, yeah, I was looking through some of the pf-design repo. issues, looks like @mcarrano is tracking a few of the inconsistencies.   @mcarrano to you happen to know if this one is in the pf design backlog?  -thanks

**Comment by dtaylor113** [comment]
Issue in Patternfly Design: https://github.com/patternfly/patternfly-design/issues/576

**Comment by mcarrano** [comment]
We are in the process of addressing this on the design side. But I believe that this issue should be closed. The second line of the toolbar is intended to be present at all times whether filters are applied or not. That space can also be used to optionally display a pagination control when pagination is supported. Apologize for all the inconsistencies that crept in on this.

**Comment by beanh66** [comment]
@mcarrano thanks, I'll close this for now.
