### ISSUE TITLE
Filtering does not work consistently and provides unexpected results

### ISSUE THREAD

**Issue by julienlim** [patternfly/angular-patternfly#727]
Noting here that there's a bug with the filtering component in that it does not work consistently and provides unexpected results -- see https://github.com/Tendrl/ui/issues/866#event-1515448349 for additional details.

**Comment by dtaylor113** [comment]
Hi @julienlim, can you please elaborate on what the issue is?   I see from #866 that you entered a '1' and then a '4912'; where you expecting a single result?   
Just FYI, the logic to apply the filter to the results set is done in the application code, not patternfly itself, to that end, could you please supply a link to the code which runs the filter shown in #866  -thanks!

**Comment by a2batic** [comment]
@dtaylor113, we have implemented the filter component according to the example provided here[1]. The filter is accepting multiple values for 'text' filters, which is giving unexpected results. The code file for #866 is [2].

[1] https://www.patternfly.org/angular-patternfly/#/api/patternfly.filters.component:pfFilter
[2] https://github.com/Tendrl/ui/blob/master/src/modules/hosts/host-list/host-list.js#L108

**Comment by dtaylor113** [comment]
Hi @a2batic, multiple 'text' filter values are AND'ed together, so in the example below Name needs to contain 'F' AND 'Fred':
![image](https://user-images.githubusercontent.com/12733153/37358749-3d55d772-26c2-11e8-9d1f-8af7f7442e8b.png)

In your example you entered a '1' and `49152' for the Brick Path, I can't tell from the screenshots if there are Brick Paths which contain a '1' AND also '49152'.

**Comment by a2batic** [comment]
@dtaylor113, yeah, so in the Brick Paths '1' is there but '49152' isnt there, so the AND of the two value resulted in false.
For ex:-
![screenshot from 2018-03-13 23-54-36](https://user-images.githubusercontent.com/12200504/37361907-f84ccb60-2719-11e8-96e9-f6b389bdbb9e.png)

**Comment by dtaylor113** [comment]
Hi @a2batic, ok, so is there an issue?

**Comment by dtaylor113** [comment]
We do have the [pfFilterPanel](https://www.patternfly.org/angular-patternfly/#/api/patternfly.filters.component:pfFilterPanel) if you want to OR values together.  aka. [Checkbox Filter](http://www.patternfly.org/pattern-library/forms-and-controls/filter/#/design)

**Comment by dtaylor113** [comment]
Hi @julienlim, so is there an issue with angular-patternfly's filter component?

**Comment by julienlim** [comment]
@dtaylor113 The problem seems not to be with the angular-patternfly filter component.  Thank you for your help!

**Comment by a2batic** [comment]
Thankyou @dtaylor113, we did not look into checkbox filter !
