### ISSUE TITLE
pfVerticalNavigation: doesn't fully collapse when items don't have icons

### ISSUE THREAD

**Issue by alexkieling** [patternfly/angular-patternfly#744]
When the vertical navigation items don't have icons, the vertical navigation should be fully collapsed but it's not.
See the **Without Primary Menu Icons** example in the PatternFly website:
http://www.patternfly.org/pattern-library/navigation/vertical-navigation/#code

**Comment by jeff-phillips-18** [comment]
Seems to work ok for me. Are you passing `hidden-icons="true"` to the pfVerticalNavigation component?

**Comment by alexkieling** [comment]
OK. I didn't see that configuration.
