### ISSUE TITLE
pfVerticalNavigation: on mobile, move the masthead utility items to the vertical navigation

### ISSUE THREAD

**Issue by alexkieling** [patternfly/angular-patternfly#745]
On mobile (less than 768 px), the masthead utility items (Help, About, Logout, etc.) are hidden but the pfVerticalNavigation component doesn't support dynamically showing them in the vertical navigation. I suggest adding a new property to the `items` objects to flag what items should be hidden by default and shown on mobiles.
More details in the [PatternFly Vertical Navigation design docs](http://www.patternfly.org/pattern-library/navigation/vertical-navigation/#design
).

**Comment by dtaylor113** [comment]
Hi @alexkieling,
Is this what you had in mind?  I added a `mobileOnly` flag to the items.

Note that **'Help'** and **'User'** vert. nav items only appear when in mobile (< 768px) mode, and are hidden when not in mobile mode:
![mobileonly](https://user-images.githubusercontent.com/12733153/41430999-96a34efc-6fdf-11e8-98a9-54bfaa9fc0da.gif)

**Comment by alexkieling** [comment]
Yes, that's exactly what I had in mind. It seems to match the [PatternFly design](http://www.patternfly.org/pattern-library/navigation/vertical-navigation/#design) perfectly.
@tadayosi, what do you think?

**Comment by tadayosi** [comment]
@alexkieling Looks good to me. Thanks.

**Comment by dtaylor113** [comment]
Fixed via #747, not sure why it didn't auto-close
