### ISSUE TITLE
pfVerticalNavigation: masthead utility items are hidden when `ignore-mobile` is true

### ISSUE THREAD

**Issue by alexkieling** [patternfly/angular-patternfly#746]
**Current behavior**
Masthead utility items are hidden on mobile when `ignore-mobile` parameter is true
**Expected behavior**
Masthead utility items should not be hidden on mobile when `ignore-mobile` parameter is true

**Comment by dtaylor113** [comment]
From @jeff-phillips-18, posting here so we don't lose this bit of work  -thanks Jeff

"I played around with the ignoreMobile stuff in A-PF
I have the `less` necessary to hide/show in the header based on resolution and the ignoreMobile flag 
Have to add `ignore-mobile` on `navbar-header` and `navbar-collapse`
then the less is:
```
.navbar-header {
  &.ignore-mobile {
    float: left;
  }
}

.navbar-collapse {
  &.ignore-mobile {
    width: auto;
    border-top: 0;
    box-shadow: none;

    .navbar-nav {
      float: left;
      margin: 0;

      &.navbar-right {
        float: right;
        .dropdown-menu {
          left: auto;
          right: 0;
        }
      }

      > li {
        float: left;
      }

      .open .dropdown-menu {
        position: absolute;
        margin-top: 0;
        background-color: @color-pf-white;
        border: 1px solid @color-pf-black-400;
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
      }
    }
  }
}
```
