### ISSUE TITLE
pfVerticalNavigation - Basic: item-click-callback invoked on hover

### ISSUE THREAD

**Issue by alexkieling** [patternfly/angular-patternfly#754]
**Current behavior**
The function defined in the `item-click-callback` attribute is invoked on mouse hover.

**Expected behavior**
The function defined in the `item-click-callback` attribute should be invoked only on mouse click.

**Comment by dtaylor113** [comment]
Hi @alexkieling, I currently have a `console.log` whenever `navigate-callback` is executed, and I don't see it being called on a mouse hover?

**Comment by alexkieling** [comment]
Sorry. I was defining the callback function incorrectly.
