### ISSUE TITLE
Notification drawer example dropdown kebab broken

### ISSUE THREAD

**Issue by skateman** [patternfly/angular-patternfly#759]
I was playing with the [notification drawer example](https://www.patternfly.org/angular-patternfly/#/api/patternfly.notification.component:pfNotificationDrawer) and found two issues, in [`notification-body.html`](https://github.com/patternfly/angular-patternfly/blob/master/test/notification/notification-body.html):
* The `dropdownKebabRight` ID is being used in the repeated region, i.e. possibly generates duplicate IDs
* The `data-toggle="dropdown"` attribute on the `<button>` [conflicts](https://github.com/angular-ui/bootstrap/issues/2156#issuecomment-42399777) with the JS provided by bootstrap. This causes the kebab to activate after a second click only.

**Comment by dtaylor113** [comment]
> ...This causes the kebab to activate after a second click only.
Hi @skateman, sorry, I'm not seeing this behavior?  The kebab opens on the first click for me?
![image](https://user-images.githubusercontent.com/12733153/44268158-9fd37280-a1fe-11e8-9ea2-0ab8d35a118d.png)

**Comment by dtaylor113** [comment]
Hi @skateman, ok I removed `data-toggle="dropdown"` from the `<button/>` in `notification-body.html` for the Notification Drawer ngDoc example and the kabob menu continues to work on a single click.   
`<button/>` in `notification-body.html` still has `uib-dropdown-toggle` which I believe is the correct angular-ui bootstrap attribute.

I'll work on dropdownKebabRight ID issue next.
Thanks,
Dave

**Comment by skateman** [comment]
@dtaylor113 yes, the `uib-dropdown-toggle` is okay, I fixed the attribute to the `data-toggle` above, sorry and thanks

**Comment by dtaylor113** [comment]
> I fixed the attribute to the data-toggle above, sorry

Sorry, where did you fix it?

**Comment by skateman** [comment]
@dtaylor113 in the PR description I had `dropdown-toggle` instead of `data-toggle="dropdown"`

**Comment by dtaylor113** [comment]
Hi @skateman, do you need `id="dropdownKebabRight"`?  I removed it from notification drawer example, and the example and our unit tests continue to work correctly.

**Comment by skateman** [comment]
Not sure about the `aria-` prefix on the dropdown content, it has probably some semantic value. Ideally here you would have to generate a dynamic ID for each notification as we do it [here](https://github.com/ManageIQ/manageiq-ui-classic/pull/4492/files#diff-0e1806e1cadcb86af090bf0c84e39630R4). I know it's not pretty, but it would be nice if we could prevent people from copy-pasting bad stuff (we have a bunch of copy-pasted PF examples that cause duplicate ID issues and that makes QE cry sometimes).

**Comment by dtaylor113** [comment]
I'm still not sure that example generates a unique id across all kabob action dropdowns.  It's based on notification.id, where it should be something like `'dropdownKebabRight-{{ notification.id }}-{{ notification.action.id }}'` because there may be mutliple actions per notification.

**Comment by skateman** [comment]
Yup, but only one dropdown per-notification and the ID belongs to the dropdown.

**Comment by dtaylor113** [comment]
ah, yes, correct, it's been a while :-)
