### ISSUE TITLE
pfTableView: dropdown buttons shorter than table cells

### ISSUE THREAD

**Issue by alexkieling** [patternfly/angular-patternfly#762]
The last column of the table containing the menu actions shows buttons that are shorter than the containing cell height. The issue can be seen when one of the row cells contains more than one line and forces a higher height for the whole row. I've attached a screenshot with buttons styled with red borders to show the issue.
It looks like dynamically changing the `<div uib-dropdown>` class to 'dropdown' and 'dropup' is causing the issue. It could be a browser bug, I'm not sure. When I set the default value of `ctrl.dropdownClass` to `dropdown`, it fixes the initial rendering. Forcing a class change to `dropup` inexplicably changes the button heights.

![table_dropdown_buttons](https://user-images.githubusercontent.com/1910095/46674216-f97a6c80-cbb1-11e8-8db2-a3788917c47a.png)

**Comment by dtaylor113** [comment]
Hi @alexkieling, I do see the same spacing in Chrome v69 Linux.  However, I see `<div uib-dropdown>`'s classes change from `dropdown-kebab-pf dropdown` to `dropdown-kebab-pf dropdown open`  -just toggling the `open` class.  I'm not following the `dropup` and `ctrl.dropdownClass` comments.  

I do notice if I toggle on/off the `padding: 0` of the parent `<td>`'s ...`table-view-pf-actions` class, it renders correctly.

-thanks

**Comment by alexkieling** [comment]
@dtaylor113 the `dropdown` class is being replaced by `dropup` when the button is close to the bottom of the window and would be hidden from the user.
https://github.com/patternfly/angular-patternfly/blob/22ca454c7b9b8d572b7efa5accebf8e48584cde4/src/table/tableview/table-view.component.js#L470-L484

**Comment by alexkieling** [comment]
I found a solution. It looks like the `dropup` class doesn't set `height` to 100%, only `dropdown`. When the class is changed from `dropdown` to `dropup` the button height is affected. Also, it looks like `ctrl.dropdownClass` needs a default value. I'll send a PR.

**Comment by dtaylor113** [comment]
Ok, great!  -thanks
