### ISSUE TITLE
Documentation unreachable - 404 Error 

### ISSUE THREAD

**Issue by romanblanco** [patternfly/angular-patternfly#775]
http://www.patternfly.org/angular-patternfly is not reachable, I'm getting 404 back.

**Comment by dtaylor113** [comment]
I do see a 'PatternFly 3' link in the footer of PatternFly.Org, and was able to navigate to the PF3 Pattern Library examples, but clicking on the angular-patternfly doc link resulted in the 404 Error as well:  https://www.patternfly.org/angular-patternfly/

![image](https://user-images.githubusercontent.com/12733153/58487143-1cec2a80-8135-11e9-916d-f56b93f88774.png)

* Note I'm seeing the same for `patternfly-ng` docs as well:  https://www.patternfly.org/patternfly-ng/

Is there a new url for PatternFly 3 code examples?

cc @dgutride

**Comment by dtaylor113** [comment]
@mturley wrote: 
"Can confirm, on e.g. https://www.patternfly.org/pattern-library/navigation/vertical-navigation/#code the "View Angular PatternFly Example" and "View PatternFly NG Example" links are broken. They redirect to the `/v4/404.html` page, so it looks like something about how we set up routes for the new v4 site"

**Comment by dtaylor113** [comment]
Hi @romanblanco,
This url works:  https://www.patternfly.org/components/angular-patternfly/dist/docs/#/api
We're working on restoring the broken links in pf.org.
Thanks,
- Dave

**Comment by redallen** [comment]
Fixed https://patternfly.org/angular-patternfly and https://patternfly.org/patternfly-ng with some redirects for now.
